### ISSUE TITLE
Bug: Workingtime from Timer displays 'NaN'

### ISSUE THREAD

**Issue by thomashoullier** [kromitgmbh/titra#103]
Since a few days ago, I experienced a bug with the Workingtime/Timer in Firefox v97.0.
Steps to reproduce:
* Start the timer
* Stop the timer whenever, can be 1 second, can be 2 hours.
* The 'Workingtime' field displays 'NaN' instead of the value in hours as it used to.

This is not intermittent, it happens everytime. I can reproduce this behaviour both on my instance and on https://app.titra.io/.
However, everything seems to work fine on Chromium.

If you need error traces from my browser etc. I am happy to provide them but you will have to guide me.

**Comment by faburem** [comment]
thanks for reporting this issue, it is fixed in titra version 0.70.1!
