### ISSUE TITLE
Start and end time of each task

### ISSUE THREAD

**Issue by TechNicLedro** [kromitgmbh/titra#104]
Hi, I really linke this product. Would it be possible to add a start and end time to each task and not only it's time duration?
Best regards and keep up with the good work.

**Comment by faburem** [comment]
Hi,
you can already track the start time of a task by setting the global setting "Track start time?" to true:
<img width="1160" alt="image" src="https://user-images.githubusercontent.com/11456790/155577298-32822121-3c9c-46ac-9961-078ae74423db.png">
this will then show the start time (defaulting to the current time) in the track time (day) view:
<img width="1185" alt="image" src="https://user-images.githubusercontent.com/11456790/155577464-552365b6-3493-451e-b154-ed4276ae74dd.png">

Best,
Fabian

**Comment by TechNicLedro** [comment]
Thanks for the fast reply, I'll try it out.
