### ISSUE TITLE
Shared dashboard date range does not match original date range

### ISSUE THREAD

**Issue by kenske** [kromitgmbh/titra#105]
If I open the detailed report for last month (/list/timecards/all?period=lastMonth), and then click on share, the resulting link takes me to a dashboard where the date range is shifted by one day, and each line item is also shifted by a day.

**Comment by faburem** [comment]
Thanks for reporting this issue! It should be fixed in titra version 0.70.2 which is currently being built and rolling out on docker hub. If you are still experience problems feel free to re-open this issue or create a new one!
