### ISSUE TITLE
Dialog disappear when clicking on task list when on calendar view

### ISSUE THREAD

**Issue by AndreasBomholtz** [kromitgmbh/titra#107]
In the calendar view, when I click on the task list, the dialog just disappears and the screen is locked.

**Comment by faburem** [comment]
Can you please provide a screenshot? Thanks!

**Comment by faburem** [comment]
never mind, I was able to reproduce it. This is caused by the fact that bootstrap 5 does not support multiple modals anymore. I will look into possible solutions to fix this! Thanks for reporting this issue!

**Comment by faburem** [comment]
This issue is fixed in titra version 0.71.1! If you are still having problems and/or find anything else feel free to open another issue.

Thanks for supporting this project,
Fabian
