### ISSUE TITLE
Is there a way to stop new user registration?

### ISSUE THREAD

**Issue by gagan0123** [kromitgmbh/titra#11]
I'm self hosting the project for personal time entries management as well as for a few colleagues. I don't want anyone else to be able to register on the site.
Is there a way to prevent self registrations?
Is something like this in roadmap?

**Comment by faburem** [comment]
It is now :) [Add an option to disable user registration](https://github.com/kromitgmbh/titra/projects/1#card-35227924)
Thanks for your input, you can follow the progress in our [roadmap](https://github.com/kromitgmbh/titra/projects/1)!

**Comment by faburem** [comment]
The new global setting is available in titra version [0.16.0](https://github.com/kromitgmbh/titra/releases/tag/0.16.0) in the Administration > Globalsettings page.
<img width="1373" alt="Screenshot 2020-03-28 at 18 59 39" src="https://user-images.githubusercontent.com/11456790/77830089-62e39780-7126-11ea-9846-e1c0d9b620f4.png">
The Docker image is currently being built and will be available within the next hour 👍

**Comment by gagan0123** [comment]
This is awesome :)
Thanks for such quick pace development of this enhancement.
