### ISSUE TITLE
https://app.titra.io/ showing 404 error

### ISSUE THREAD

**Issue by surentharp** [kromitgmbh/titra#119]
Hi,

Thank you once more for this wonderful app; it is very useful for my personal needs.

The Titra app (https://app.titra.io/) is returning a 404 error. I believe you are working on the server; if not, this information may be useful in resolving this issue.

Thanks,
Suren

**Comment by stuehr** [comment]
since this morning our titra installation returns "502 Bad Gateway"
Maybe it is related to the latest release?

**Comment by faburem** [comment]
yes it is related, I have just updated to the latest version 0.74.2 and it is up and running again. Sorry for the inconvenience!
