### ISSUE TITLE
Titra container error

### ISSUE THREAD

**Issue by TechNicLedro** [kromitgmbh/titra#120]
Hi,

I've been using titra for some time now and everything has always worked fine.
Starting some days ago I get an error message when the titra container is start which cause it to continuously restart. 

Here's the error code:
`Starting titra...
titra         | /app/bundle/programs/server/node_modules/fibers/future.js:280
titra         | 						throw(ex);
titra         | 						^
titra         | 
titra         | Error: Cannot find module "/node_modules/meteor/minifier-css/node_modules/postcss/lib/postcss.js". Try installing the npm package or make sure it is not a devDependency.
titra         |     at Module.useNode (packages/modules-runtime.js:647:11)
titra         |     at module (packages/minifier-css/minifier.js:297:1)
titra         |     at fileEvaluate (packages/modules-runtime.js:336:7)
titra         |     at Module.require (packages/modules-runtime.js:238:14)
titra         |     at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
titra         |     at packages/minifier-css/minifier.js:1:230
titra         |     at module (packages/minifier-css/minifier.js:297:1)
titra         |     at fileEvaluate (packages/modules-runtime.js:336:7)
titra         |     at Module.require (packages/modules-runtime.js:238:14)
titra         |     at require (packages/modules-runtime.js:258:21)
titra         |     at packages/minifier-css/minifier.js:297:1
titra         |     at packages/minifier-css/minifier.js:297:1
titra         |     at /app/bundle/programs/server/boot.js:401:38
titra         |     at Array.forEach (<anonymous>)
titra         |     at /app/bundle/programs/server/boot.js:226:21
titra         |     at /app/bundle/programs/server/boot.js:464:7
titra exited with code 1
`

Thanks in advance for the help.
Nicola

**Comment by faburem** [comment]
Hi Nicola,
just update the container one more time, that was a regression caused by the latest Meteor.js framework  changes. It is fixed starting with titra version 0.74.2 (of course also in the latest version 0.74.3).

Best,
Fabian

**Comment by TechNicLedro** [comment]
Thanks for the fast reply. That solved my problem.
Best regards,
Nicola
