### ISSUE TITLE
Date selection broken when Editing Date from Details page (0.74.3)

### ISSUE THREAD

**Issue by lylebrown** [kromitgmbh/titra#123]
When editing a previous time entry from the Details page, the only date allowed to be selected is the current date ("Today"). Changing this date appears to do nothing, and if the entry is saved, it is saved with the current date ("Today"). However, when editing another entry (or the same one) immediately after, the only date that can be selected is the date that was selected when editing the prior entry. Saving the record sets the date to the one displayed (that was selected when attempting to set it in the previous entry.)

No browser console logs, nor application logs are created when reproducing this issue.

**Comment by faburem** [comment]
This should be fixed in titra version 0.75.1! Feel free to open another issue if the problem persists.

Thanks!
