### ISSUE TITLE
Login Page not displayed correctly

### ISSUE THREAD

**Issue by tuccler** [kromitgmbh/titra#126]
Hello,
i'm trying to set up titra on my unraid server. After a few trys i managed to define the variables right to deploy the container.

> Repository: kromit/titra
> Icon URL: https://raw.githubusercontent.com/kromitgmbh/titra/master/public/favicons/favicon.ico
> ROOT_URL: http://192.168.0.2
> MONGO_URL: mongodb://192.168.0.2/titra?directConnection=true
> PORT: 3000

The container starts but something is still wrong. When i open the WebUI im getting this:
![grafik](https://user-images.githubusercontent.com/60432330/163348294-98260ff7-0361-4adf-98ec-37422eb65ce7.png)

I tried to use kromitgmbh/titrafor pulling the image but then i get this error message:

> docker run -d --name='titra' --net='bridge' -e TZ="Europe/Berlin" -e HOST_OS="Unraid" -e 'ROOT_URL'='http://192.168.0.2' -e 'MONGO_URL'='mongodb://192.168.0.2/titra?directConnection=true' -p '3000:3000/tcp' 'kromitgmbh/titra' 
> 
> docker: Error response from daemon: pull access denied for kromitgmbh/titra, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

Has someone an idea what I'm missing or what I'm doing wrong? 

Greatings
tuccler

**Comment by faburem** [comment]
Hi,
can you point me to the documentation where the docker image is referenced as kromitgmbh/titra? It should be kromit/titra, this is our handle on the docker hub.
Besides that, you have to use the external IP of your unraid server as the ROOT_URL and likely have to add the port (3000) which you also have to open in your firewall configuration. As an alternative you can use any reverse proxy (nginx, apache, traefik, ...) to forward the requests from port 80/443.

I hope this help!

Best,
Fabian

**Comment by tuccler** [comment]
Yes, kromit/titra is working for me. I mixed it up with your handle here. 

Refering to the dockerhub it should work with the localhost:
>titra should now be up and running at http://localhost:3000/

With both "http://localhost" and "http://192.168.0.2" as a value for ROOT_URL the docker container starts. 
Also the Port Mappings look fine: 172.17.0.4:3000 <> TCP192.168.0.2:3000 

I can access the WebUi under http://192.168.0.2:3000 or http://localhost:3000 but the UI won't load properly like you can see on the picture in my inital post.  Or do i need the ports 80/443? Because they are already used.

**Comment by faburem** [comment]
so have you tried adding the port to the ROOT_URL i.e. ROOT_URL="http://192.168.0.2:3000"? I just wanted to point out that it will only be accessible from the local machine in that case.

**Comment by tuccler** [comment]
@faburem  Sorry, for the late replay. Yes, i tried also ROOT_URL="http://192.168.0.2:3000/". 
I get those error messages:

> Uncaught (in promise) Error: Cannot find module '/node_modules/bootstrap/dist/js/bootstrap.esm.js'

> Uncaught (in promise) Error: Cannot find module '/imports/ui/styles/light.scss'

**Comment by faburem** [comment]
can you try it with the ROOT_URL set to http://localhost:3000/ ?
The error you are seeing means that the node server cannot access the assets at the defined root URL. This can be related to docker networking that's why I'm curious if it might work with localhost. You can also check if there is an IP defined for the docker <> host communication, I know this network setup for digital ocean / CoreOS at least. Btw which operating system is the docker container running on?

**Comment by tuccler** [comment]
It's working now. I deleted both the MongoDB and titra container and build them from scratch. This are the Variables I'm using now:

ROOT_URL: http://192.168.X.X:3000
MONGO_URL: mongodb://192.168.X.X/titra?directConnection=true
PORT: 3000

+ I added (I don't think it was this):
MONGO_OPLOG_URL: mongodb://localhost:27017/local

The last try was mit "ROOT_URL: http://http://localhost:3000" with "ROOT_URL:192.168.X.X:3000"

Thank you for your support. 🙏I'm Happy that i can now take a deeper look into the tool itself. :)

**Comment by faburem** [comment]
Great, thanks for your feedback! Closing this issue now.
