### ISSUE TITLE
Billing on task level?

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [kromitgmbh/titra#127]
I just started using the official titra app and really like the simplicity, dark theme and loading time!
Great job so far!

I wonder if it was feasible to also offer editing the billing information for separate tasks instead of only the whole project?

If I e.g. do some work for a project that is not billable or pro bono, i would still like to track it in the project.
So for me also an "Exclude billing for this task" option would work.

Or is there a way to do this in the existing solution that i haven't found yet?

Probably would also work with the custom field for tasks, but as far as i understood that's an admin option and would only work on self hosted instances?

For now i think i will just create a separate project for tasks with different billing.

**Comment by faburem** [comment]
Hi,
Thanks for your feedback! As you already pointed out correctly one of our main goals for titra is to keep it simple. Therefore we try to limit the complexity for tracking time as much as possible. I personally think the usage of a dedicated project for non billable work makes perfect sense. You rarely need to report your non billable time on a customer/project basis. You can still do that using custom fields or through the task description in your non billable work project. We do the same internally with a team of 10 today and did not find any reason to change it. Even if you want to make a time entry non-billable later on you can move it from the customer project to the non-billable project.
On a side note - would you be interested in a hosted version of titra so you have full access to all administration features? We are currently working on a SaaS offering and would love some early adopters on board!

Best,
Fabian

**Comment by TheGreatRefrigerator** [comment]
Hi @faburem,

thank you for the answer. I will continue using the separate project then.
Good to know that i can move entries between projects 😄 
For now the online version is sufficient, as i only use it for myself.
But if i run into some issues, where i would need the admin features i will come back to you.

Best regards
