### ISSUE TITLE
Action buttons "Edit"/"Delete" not showing any text on mobile (or small window)

### ISSUE THREAD

**Issue by domi4484** [kromitgmbh/titra#129]
![Peek 2022-04-25 21-24](https://user-images.githubusercontent.com/9881900/165159685-ea52917b-839a-4a87-aed1-f52803deca00.gif)

**Comment by faburem** [comment]
Will be fixed in the next titra version! Thanks for reporting this issue!

**Comment by faburem** [comment]
This is fixed in titra version 0.75.2!

**Comment by domi4484** [comment]
Thank you very much! 🙏
