### ISSUE TITLE
Rounding

### ISSUE THREAD

**Issue by gnius** [kromitgmbh/titra#130]
Awesome idea, and appears to run well. 
Oftentimes time-based billing allows you to round up to the nearest 15 minutes. Do you think rounding is something to you are planning to add as a feature? Thanks in advance.

**Comment by gnius** [comment]
> sounds reasonable. We just have to figure out the best way to make this work in a generic way so we can support rounding to the nearest 15 minutes as well as the closest hour. Also this should definitely be opt-in because not everyone will expect / appreciate this behaviour. It's on our Roadmap now!

Thank you for replying! 

Thinking the way that would be most useful to freelancers would be something as follows
1. checkbox to opt into rounding
2. checkbox for minimum elapsed time with a dialog box to enter number of minutes
3. dialog box to enter rounding increment (number of minutes) or drop-down box for (5 minutes, 10 minutes, 15 minutes, 30 minutes, 1 hour)
4. drop-down box to round up or down (I don't think anyone is rounding down)?
5. In reports have 2 columns - actual time, and billed time to show the rounding. May need to make the actual time column optional to submit to clients

**Comment by faburem** [comment]
This has been implemented and shipped in titra version 0.86.0!
Feel free to re-open or create a new issue if you encounter any problems with this new feature!
