### ISSUE TITLE
Client selection

### ISSUE THREAD

**Issue by TechNicLedro** [kromitgmbh/titra#131]
Good morning,

would it be possible to choose the client when creating a project from the previus client used? At this moment it seems to me that I have to type the client in the same way so when I group projects by client they are shown togheter. It would be nice a behaviour such as the one of the tasks where you start typing and it shows previously used tasks, or it let's create a new one.

Thanks for the great project
Nicola

**Comment by faburem** [comment]
Thanks for the suggestion - has been bugging me as well to be honest 😛 
I will prototype a bit and might add this in the next release as early as this week.

**Comment by TechNicLedro** [comment]
Thanks, it's greatly appreciated.

**Comment by faburem** [comment]
This has shipped in titra version 0.76.1!
