### ISSUE TITLE
How to get in touch regarding a security concern

### ISSUE THREAD

**Issue by JamieSlome** [kromitgmbh/titra#133]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@saharshtapi) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by faburem** [comment]
added SECURITY.md to the repo - thanks for pointing this out.
You can send security related issues to security@titra.io, however we also greatly appreciate any PRs with suggested security enhancements.

Thanks,
Fabian

**Comment by JamieSlome** [comment]
@faburem - thanks for your diligence! ⚡ 

We will get both reports sent over shortly :)
