### ISSUE TITLE
Blank Track/Week tab

### ISSUE THREAD

**Issue by thomashoullier** [kromitgmbh/titra#134]
The tab in Track/Week is blank of time data.
This is the case for all weeks, even those that were previously displayed correctly.

The tabs 'Day' and 'Month' work as expected.
I can get the weekly totals in Details/Time period -> Current week, this works as usual.

Titra version: `0.77.0`, using `docker-compose`.
Browsers: Firefox or Chromium.

See the following screenshot of the issue (I hid the projects/tasks names with the pink rectangle, these were displayed without error):
![image](https://user-images.githubusercontent.com/48186690/172927565-fe9d8ef2-8d6c-44ab-8ea8-3f0df6ada648.png)

**Comment by thomashoullier** [comment]
This is also the case on https://app.titra.io

**Comment by faburem** [comment]
fixed in titra version 0.78.0!
