### ISSUE TITLE
Error by changing status

### ISSUE THREAD

**Issue by martinh-dev** [kromitgmbh/titra#138]
When I try to change the status of an entry (ex.: from "New" to "Billed") I get the following error message:

/imports/ui/components/detailtimetable.js:1 r {isClientSafe: true, error: 400, reason: 'Match failed', details: undefined, message: 'Match failed [400]', …}
eval @ /imports/ui/components/detailtimetable.js:1
(anonym) @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:1
_maybeInvokeCallback @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
receiveResult @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
_livedata_result @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
onMessage @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
(anonym) @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
forEachCallback @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
socket.onmessage @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
r.dispatchEvent @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
k._dispatchMessage @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
k._didMessage @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
t.onmessage @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
r.dispatchEvent @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
n.xo.onchunk @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
i.emit @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
s.xhr.onreadystatechange @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
XMLHttpRequest.send (async)
_start @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
(anonym) @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
setTimeout (async)
n.delay @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
n.XHRCorsObject @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
re @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
Q._scheduleRecv @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
t.onclose @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
r.dispatchEvent @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
n.xo.onfinish @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
i.emit @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
s.xhr.onreadystatechange @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
XMLHttpRequest.send (async)
_start @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
(anonym) @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
setTimeout (async)
n.delay @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
n.XHRCorsObject @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
re @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
Q._scheduleRecv @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
t.onclose @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
r.dispatchEvent @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
n.xo.onfinish @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
i.emit @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
s.xhr.onreadystatechange @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
XMLHttpRequest.send (async)
_start @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
(anonym) @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
setTimeout (async)
n.delay @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
n.XHRCorsObject @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
re @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
Q._scheduleRecv @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
t.onclose @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
r.dispatchEvent @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
n.xo.onfinish @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
i.emit @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
s.xhr.onreadystatechange @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
XMLHttpRequest.send (async)
_start @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
(anonym) @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
setTimeout (async)
n.delay @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
n.XHRCorsObject @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
re @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
Q._scheduleRecv @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
t.onclose @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
r.dispatchEvent @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
n.xo.onfinish @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
i.emit @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
s.xhr.onreadystatechange @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
XMLHttpRequest.send (async)
_start @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
(anonym) @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
setTimeout (async)
n.delay @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
n.XHRCorsObject @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
re @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
Q._scheduleRecv @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
t.onclose @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
r.dispatchEvent @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
n.xo.onfinish @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
i.emit @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
s.xhr.onreadystatechange @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
XMLHttpRequest.send (async)
_start @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
(anonym) @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
setTimeout (async)
n.delay @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
n.XHRCorsObject @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
re @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
Q._scheduleRecv @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
t.onclose @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
r.dispatchEvent @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
n.xo.onfinish @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
i.emit @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
s.xhr.onreadystatechange @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
XMLHttpRequest.send (async)
_start @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
(anonym) @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
setTimeout (async)
n.delay @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
n.XHRCorsObject @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
re @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
Q._scheduleRecv @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
t.onclose @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
r.dispatchEvent @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
n.xo.onfinish @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
i.emit @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
s.xhr.onreadystatechange @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
XMLHttpRequest.send (async)
_start @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
(anonym) @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
setTimeout (async)
n.delay @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
n.XHRCorsObject @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
re @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
Q._scheduleRecv @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
t.onclose @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
r.dispatchEvent @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
n.xo.onfinish @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
i.emit @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
s.xhr.onreadystatechange @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
XMLHttpRequest.send (async)
_start @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
(anonym) @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
setTimeout (async)
n.delay @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
n.XHRCorsObject @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
re @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
Q._scheduleRecv @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
t.onclose @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
r.dispatchEvent @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
n.xo.onfinish @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
i.emit @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
s.xhr.onreadystatechange @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
XMLHttpRequest.send (async)
_start @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
(anonym) @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
setTimeout (async)
n.delay @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
n.XHRCorsObject @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
re @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
Q._scheduleRecv @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
Q @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
run @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
k.xhr-polling @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
k._try_next_protocol @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
k._didClose @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
k._didMessage @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22
o.ws.onclose @ fba65f1df2fad2ea49c0106a8738daeca67c7732.js?meteor_js_resource=true:22

After a reload the change I made is not stored.

**Comment by faburem** [comment]
This is fixed in titra version 0.79.2.
Thanks for reporting this issue and thus improving titra!

Best,
Fabian
