### ISSUE TITLE
Allow timer to continue when browser is closed

### ISSUE THREAD

**Issue by willhseitz** [kromitgmbh/titra#14]
Maybe with server-side timer or browser cookie/storage?

**Comment by willhseitz** [comment]
Another simple option could be to add a warning when closing a tab. something like what is explained here https://stackoverflow.com/questions/7317273/warn-user-before-leaving-web-page-with-unsaved-changes

**Comment by faburem** [comment]
Thanks, I think that is a great idea! I just added it to our [roadmap](https://github.com/kromitgmbh/titra/projects/1#card-38582330).

**Comment by faburem** [comment]
Implemented in version 0.21.0 of titra, which is currently being built on docker hub.
