### ISSUE TITLE
Autofill for project name

### ISSUE THREAD

**Issue by puredomain** [kromitgmbh/titra#145]
Thanks for this project which is perfect for a freelancer or a small team. 

If I may suggest a UI/UX feature enhancement - currently, for a time entry, you need to select a project as a dropdown menu. This may be a bit difficult when there are tens of projects that need to be tracked. It would be great if the UI would allow you to fill in the project name and display a pop-up menu of all suitable project names as you type (and when there is only one option left, select it my pressing enter).

Many thanks

**Comment by faburem** [comment]
Thanks for your feedback! I think this is a great idea. I will add it to our roadmap asap.

Best,
Fabian

**Comment by faburem** [comment]
A quick update on this one because it is taking longer than expected. It turned out there are some dependencies which prevent this to roll out as a quick fix but we use the opportunity to refactor some really old code which will enable additional cool features. It will be worth the wait!

**Comment by faburem** [comment]
this has shipped in titra version 0.80.0 today 🥳

**Comment by CaptainPackers** [comment]
I don't like this enhancement at all as I only have a few projects. I much prefer the old method where they would all show up when I opened the drop list. Now I have to delete whatever has been stored in the text box and start typing to get my project to show up. It is much less convenient for me. Any way there could be a configuration choice for the drop list behavior?

Thanks

**Comment by faburem** [comment]
I think you should get a pretty similar behavior by setting this global setting to a high number:
![Screenshot_20230308_165213_Chrome.jpg](https://user-images.githubusercontent.com/11456790/223763579-778166f3-dc8a-46df-8de9-4824a21ce84e.jpg)

**Comment by CaptainPackers** [comment]
I like it! I just don't want to have to reach for the keyboard and lay on the backspace button to get the list back when I am mousing around.

Thanks for the quick response!

**Comment by faburem** [comment]
Improvement shipped in titra version 0.90.0

**Comment by CaptainPackers** [comment]
Works great! I love it!

Thanks so much for your prompt attention.

Regards,
CaptainPackers-- 
Sent with Tutanota, enjoy secure & ad-free emails. 



Mar 10, 2023, 8:41 AM by ***@***.***:
