### ISSUE TITLE
move titra database to different server

### ISSUE THREAD

**Issue by CaptainPackers** [kromitgmbh/titra#147]
I want to move the titra database to a new server, but I can't figure out how to export and import the data. I tried to set up a dump volume like the wekan docker-compose.yml file has, and I even seemed to succeed in dumping the data, but when I tried to copy the container data to the host file system I was getting no such container path errors when executing docker cp.

Also, it titra limited to v. 4 of mongo? I updated docker-compose to pull the latest image and I've been getting core dumps ever since. Though the core dumps could be related to my attempt to add a dump volume (cf. wekan docker-compose.yml)

Can you provide any pointers with regard to migrating my data to a new server?

Thanks

**Comment by CaptainPackers** [comment]
I was able to resolve this by following the comments in the Wekan docker-compose.yml file.

Here's what I did:

On the old server (same directory as docker-compose.yml file)
* docker stop titra
* docker exec -it mongodb bash
* cd /data
* mongodump
* exit
* docker cp mongodb:/data/dump .
* docker exec mongodb rm -rf /data/dump
* docker exec mongodb mongodump -o /data/dump
* docker cp mongdb:/data/dump .
* Copy the dump directory to the new server (same directory as docker-compose.yml file)

On the new server (same directory as docker-compose-yml file)
* docker stop titra
* docker exec -it mongodb bash
* cd /data
* rm -rf dump
* exit
* docker cp dump mongodb:/data/
* docker exec -it mongodb bash
* cd /data
* mongorestore --drop
* exit
* docker start titra

**Comment by CaptainPackers** [comment]
I was able to resolve this by following the comments in the Wekan docker-compose.yml file.

Here's what I did:

On the old server (same directory as docker-compose.yml file)
* docker stop titra
* docker exec -it mongodb bash
* cd /data
* mongodump
* exit
* docker cp mongodb:/data/dump .
* docker exec mongodb rm -rf /data/dump
* docker exec mongodb mongodump -o /data/dump
* docker cp mongdb:/data/dump .
* Copy the dump directory to the new server (same directory as docker-compose.yml file)

On the new server (same directory as docker-compose-yml file)
* docker stop titra
* docker exec -it mongodb bash
* cd /data
* rm -rf dump
* exit
* docker cp dump mongodb:/data/
* docker exec -it mongodb bash
* cd /data
* mongorestore --drop
* exit
* docker start titra

**Comment by CaptainPackers** [comment]
After moving to the new server, none of my projects are available in the Project drop down list in the "+Track" tab. They show up if I start typing the project name, but there is no pre-populated list of all my projects. What can I do to fix this?

**Comment by faburem** [comment]
Hi,
I don't think this is caused by the database migration. The project select has been re-designed for an autocomplete version similar to the task search. We are currently working on new global settings to change the number of projects displayed by default. However, showing the project list should not require input - focusing the project search field should be enough to display the available projects.

Best,
Fabian

**Comment by faburem** [comment]
The new setting for the project and task search result is rolling out right now in titra version 0.80.2. Please let me know if this resolves your issue described here.

Thanks!

**Comment by CaptainPackers** [comment]
All projects are now in the drop list! Thanks!
