### ISSUE TITLE
Difficult to choose some project in the day view

### ISSUE THREAD

**Issue by domi4484** [kromitgmbh/titra#148]
Since the update to version 0.80 it is difficult to choose some projects in the "Day" view since only the first 5 are displayed by default. If someone doesn't know the names of the available projects he will not find it.
Maybe this could be a settings how many entries are shown by default?

I also had a situation where after reopening the browser an ID was displayed in the project field instead of the name. I thing I had a timer running but I can't reproduce, just made this screenshot:
![image](https://user-images.githubusercontent.com/9881900/191680982-309e687a-ff32-43bd-86cd-9aa5735b04ed.png)

**Comment by faburem** [comment]
Thanks for your feedback, we are actually working right now on the aforementioned setting for the number of projects and tasks displayed by default 😉 stay tuned for the next release soon!

**Comment by domi4484** [comment]
Oh cool thank you very much! I'm looking forward for that!

**Comment by faburem** [comment]
the feature is rolling out to docker hub right now (version 0.80.2) - along with the fix for the project id issue. Feel free to re-open this issue or create a new one if anything else feels whacky!

**Comment by domi4484** [comment]
Just tried the new version, for me all projects are visible again, but not limited to 5. Even if I change the global setting (and reload the page) all projects stay visible.
Not a problem for my usage but probably not the intended behavior :)
