### ISSUE TITLE
Customizable Wekan integration

### ISSUE THREAD

**Issue by willhseitz** [kromitgmbh/titra#15]
Some options that would be very helpful in the Wekan integration would be:

- Allow option to use multiple lists when querying a Wekan project board
- Allow [swimlanes](https://github.com/wekan/wekan/wiki/Swimlanes) to be used as titra projects, instead of an entire Wekan board

**Comment by faburem** [comment]
In general I like the ideas suggested here, however I think we need to discuss the implications of such a change. @markuskromit @thomas-kromit @philogosoph - thoughts?
