### ISSUE TITLE
GitLab issue tracking support

### ISSUE THREAD

**Issue by dabruh** [kromitgmbh/titra#152]
I and my small group of friends are thinking of trying Titra for a new project we're aiming to work on shortly. However, we're going to use GitLab for issue tracking. I see that there's support for Wekan, so I wonder if there are any ambitions to implement similar support for GitHub? How would one go about implementing this support (i.e. where to start)?

**Comment by dabruh** [comment]
Excellent!

I've recently been part of another discussion forum where yet another project is starting up. They have chosen to to with [Kanboard](https://github.com/kanboard/kanboard) (OSS) which seems like a pretty nice tool. I would have to evaluate it myself, and perhaps you would find it a good idea to have it integrated with Titra as well?

**Comment by faburem** [comment]
The task source through a new GitLab interface has shipped with titra version 0.83.0!
Feel free to re-open or create a new issue if you run into any issues. Documentation on the new feature has been added to the [titra wiki](https://wiki.titra.io/books/administration/page/gitlab-issues-import).
