### ISSUE TITLE
Small UX feature idea : add a 🔴 (or other) in the tab to indicate that the tracker is running

### ISSUE THREAD

**Issue by Julianoe** [kromitgmbh/titra#153]
Would be cool if the <title> tag in the head or the favicon was updated so that we can know, just by looking at the tab, that the tracker is running or not.

As an heavy user of Titra I often realize minutes (if not hours) after starting to work that the tracker was off. Having a visual indicator would be cool.

Is there any way we could grab the info of "the tracker is running" and when it does it adds something at the beginning of the <title> tag or remplace the favicon. When it stops running, the indicator is removed.

**Comment by faburem** [comment]
absolutely, great idea! Adding it to our roadmap!
Love the idea really, it's going to be a good enhancement.

**Comment by faburem** [comment]
this has just shipped in titra version [0.82.0](https://github.com/kromitgmbh/titra/releases/tag/0.82.0)!
