### ISSUE TITLE
Shared dashboard issues

### ISSUE THREAD

**Issue by John-H-Smith** [kromitgmbh/titra#157]
When a dashboard is shared, there are some errors/enhancements:

- Header of statistic segments (as I can see, all elements) are not translated. Maybe implement a default language to show all strings in? (Also should affect the format of dates, times and so on)
- Hovering above the bar chart will show the used hours and the boolean false:
![image](https://user-images.githubusercontent.com/18233867/221253657-5f2b2dc5-1f59-48b3-bc6b-123816d418b6.png)

Maybe, this should be fixed too.

**Comment by faburem** [comment]
Hi,
I have just pushed a fix for the second issue. For the first one regarding translations I need some help to reproduce it, for me it is translated properly to e.g. German:
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/11456790/221375698-6b82d319-b10a-4e7b-9621-e80b957f2fc6.png">
Can you please provide a bit more details or screenshots what exactly is missing a translation?

Thanks,
Fabian

**Comment by John-H-Smith** [comment]
Hi @faburem,
thanks for your quick reply and the fix.
Because of the first point: I've checked it is based on the browser langugage. This is working fine as I can see right now, only the weekday of the detailled times is always in english.

**Comment by faburem** [comment]
Thanks for your confirmation. That observation is of course correct - we are using dayjs behind the scenes to format dates but we are not loading the translation for all languages to save on bundle size and improve performance. I will evaluate if we can use the native [Intl.DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat) to format dates at least in the public dashboards to avoid this.
In the meantime, if the missing translation is an issue you can change the detailed date format in the global settings > Date settings and remove the Weekday part (ddd, ) there:
<img width="1324" alt="image" src="https://user-images.githubusercontent.com/11456790/221512588-72d04dad-d7bc-43fe-9020-d8979378fb6e.png">

That being said, can we close this issue? You can always reopen this or create a new one if you encounter any other problems.
