### ISSUE TITLE
OIDC integration?

### ISSUE THREAD

**Issue by iamscottcab** [kromitgmbh/titra#158]
I notice a global setting called "Enable Open ID Connect".

Turning this on provides no other options and I cannot find any other documentation about this in the wiki. Do you have any examples about how this works?

I'm looking at putting this behind something like [Authelia](https://www.authelia.com/) , and hoping to avoid needing to log in twice (once via authelia and then once for the local login).

**Comment by iamscottcab** [comment]
Thanks for the fast response! Embarrassingly I noticed the OIDC tab between posting and your response (I didn't see the tab as I hadn't scrolled up). But the tab was broken on my version so I appreciate pushing the fix, it's working on the latest Docker image.

As I already have a local user how does that work when I login via my OIDC provider? Will this create me a new user within Titra or will it match based on the email? I'd want my OIDC user to be the admin, but I need to login first and claim admin to make the change to OIDC in the first place so I'm not exactly sure how that works.

**Comment by faburem** [comment]
The user accounts should be merged if the email address is the same. To be completely honest this integration has been implemented by the titra community so I am not the author of it, my statement is based on the way Meteor.js accounts integrations usually work. If you could test it and it behaves differently than expected you can always come back here and we can take a look at how we can improve it.

**Comment by iamscottcab** [comment]
![Config](https://user-images.githubusercontent.com/42525567/222891893-d6b24678-5342-4aa2-ad5f-2268a7e41364.png)

Performing the above seems to throw an error in titra, specifically:

```
titra     | Exception while invoking method 'updateOidcSettings' Error: Match error: Unknown key in field service
titra     |     at check (packages/check/match.js:36:17)
titra     |     at MethodInvocation.validate (imports/api/globalsettings/server/methods.js:75:5)
titra     |     at ValidatedMethod._execute (packages/mdg:validated-method/validated-method.js:87:64)
titra     |     at MethodInvocation.updateOidcSettings (packages/mdg:validated-method/validated-method.js:57:23)
titra     |     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1902:12)
titra     |     at getCurrentMethodInvocationResult (packages/ddp-server/livedata_server.js:772:38)
titra     |     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1329:12)
titra     |     at packages/ddp-server/livedata_server.js:791:46
titra     |     at new Promise (<anonymous>)
titra     |     at Session.method (packages/ddp-server/livedata_server.js:739:23)
titra     |     at packages/ddp-server/livedata_server.js:603:43
titra     | Sanitized and reported to the client as: errorClass [Error]: Match failed [400]
titra     |     at errorClass.<anonymous> (packages/check/match.js:91:27)
titra     |     at new errorClass (packages/meteor.js:692:17)
titra     |     at check (packages/check/match.js:36:17)
titra     |     at MethodInvocation.validate (imports/api/globalsettings/server/methods.js:75:5)
titra     |     at ValidatedMethod._execute (packages/mdg:validated-method/validated-method.js:87:64)
titra     |     at MethodInvocation.updateOidcSettings (packages/mdg:validated-method/validated-method.js:57:23)
titra     |     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1902:12)
titra     |     at getCurrentMethodInvocationResult (packages/ddp-server/livedata_server.js:772:38)
titra     |     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1329:12)
titra     |     at packages/ddp-server/livedata_server.js:791:46
titra     |     at new Promise (<anonymous>)
titra     |     at Session.method (packages/ddp-server/livedata_server.js:739:23)
titra     |     at packages/ddp-server/livedata_server.js:603:43 {
titra     |   isClientSafe: true,
titra     |   error: 400,
titra     |   reason: 'Match failed',
titra     |   details: undefined,
titra     |   errorType: 'Meteor.Error'
titra     | }
titra     | 
titra     | [ERROR: Error configuring login service oidc @ Sat Mar 04 2023 09:42:19 GMT+0000 (Coordinated Universal Time)] { 
titra     |   "browserInfo": { 
titra     |     "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36", 
titra     |     "userId": "wXLNXv6qAWAYKkjz7", 
titra     |     "url": "https://my.domain/admin?activeTab=oidc-tab", 
titra     |     "resolution": "1920x1080" 
titra     |   }, 
titra     |   "stack": { 
titra     |     "isClientSafe": true, 
titra     |     "error": 400, 
titra     |     "reason": "Match failed", 
titra     |     "message": "Match failed [400]", 
titra     |     "errorType": "Meteor.Error" 
titra     |   } 
titra     | }
```

I've tried a few different combinations of empty and non empty fields and none seem to work. I've had a quick look over the stacktrace but the offending file fails in a `check` function which I assume is part of Meteor or something because I can't seem to find what happens after that.

**Comment by faburem** [comment]
Hi again,
really sorry for that inconvenience but we had some rather big structural changes in preparation for our 1.0 release of titra and it seems the OIDC integration has not been updated correctly. Unfortunately I have no setup to test it so I greatly appreciate your feedback if it is working with version 0.89.3 which I just released to fix this issue.

Best,
Fabian

**Comment by faburem** [comment]
Sorry, the version is 0.89.4 - had to push it again due to a build failure.

**Comment by iamscottcab** [comment]
Looks like we are getting closer and closer :)

I can configure my OIDC client, I am presented with a pop-up to login (and 2FA in this case, which seems to be enforced by Titra itself as I only have one factor enabled for this particular domain at present). I then get asked if I want to consent to the usual (name, email etc) and I accept. The server then throws a 500. As shown below.

```
titra  | Exception while invoking method 'login' Error: A login method must specify a userId or an error
titra  |     at packages/accounts-base/accounts_server.js:451:13
titra  |     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
titra  |  => awaited here:
titra  |     at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
titra  |     at packages/accounts-base/accounts_server.js:653:7
titra  |     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
titra  |  => awaited here:
titra  |     at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
titra  |     at getCurrentMethodInvocationResult (packages/ddp-server/livedata_server.js:781:32)
titra  |     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1329:12)
titra  |     at packages/ddp-server/livedata_server.js:791:46
titra  |     at new Promise (<anonymous>)
titra  |     at Session.method (packages/ddp-server/livedata_server.js:739:23)
titra  |     at packages/ddp-server/livedata_server.js:603:43
```

**Comment by faburem** [comment]
Hmm.. looking at the code responsible for the OIDC integration it seems that it expects an ID to be returned as part of the token response. The field can be called either id or sub in the token JSON response.
https://github.com/kromitgmbh/titra/blob/master/imports/utils/oidc_server.js#L76

Can you somehow figure out what is getting sent in the token response?

**Comment by iamscottcab** [comment]
I'll have a look but given they are standard claims on a token I'd be surprised I'd they weren't there.

Out of interest if I were to clone this repo can I run the full stack locally so I can debug the oidc server or are there other dependencies I'd need?

**Comment by faburem** [comment]
Yes, of course you can run it locally. Just clone the repo and make sure you have MeteorJS installed (https://www.meteor.com/developers/install) and cd into the cloned folder.

Then install the npm dependencies with
`meteor npm i`

And you should be up and running on http://localhost:3000 after executing 
`meteor`

**Comment by iamscottcab** [comment]
Ok so running this locally with `meteor debug` I can see that the function `registerOidc()` (which I assume from it's name is trying to register the user for the first time?) returns the following:

```
{
    "serviceData": {
        "accessToken": "myAccessToken",
        "email": "my@email",
        "expiresAt": 1234,
        "id": "1234-5678-1010101",
        "username": "my username"
    },
    "options": {
        "profile": {
            "name": "my name",
            "emails": [{
                "address": "my@email",
                "verified": true
            }]
        }
    }
}
```

There are no undefined fields here and this all looks how I would expect it to. Additionally playing around with whatever I pass into object breaks the login in different way (changing the key from `id` to `userId` for example says the model is incorrect, which is good).

Is there a way I can dig into the login function specifically? I'm not sure where these functions we are registering get called from so it's hard to tell what's going on. Though

**Comment by iamscottcab** [comment]
Ok, I think I finally tracked down the root of the problem, one of the validation methods was returning `undefined` because it was being called improperly. See #162 for the relevant fix (I didn't bump version numbers or anything but if this could be pushed to Docker that'd be great).

To anyone who might find this in the future to get OIDC integration working you'll want to do the following:

1. Configure your OIDC client for **Authorization Code Flow**
2. Set the relevant fields
- **Client ID**: Client ID as per your OIDC App Configuration
- **Client Secret**: As per your OIDC App Configuration
- **OIDC Server Url**: Your auth domain e.g. http://auth.your.domain
- **Authorization Endpoint**: /your/auth/endpoint _Note the prepended slash_
- **Token Endpoint**: /your/token/endpoint _Note the prepended slash_
- **UserInfo Endpoint**: /your/userinfo/endpoint _Note the prepended slash_
- **Id Token Fields**: Extra fields to be grabbed from your token and appended to the user. In my case my server returns an opaque access token which it grabs first (not the id token) so make sure that these fields are on the relevant token.

Users who's emails match will login to their existing accounts, otherwise a new account will be created. Just note that existing accounts can be logged into via the normal login form so if you're making dummy accounts (for any reason) make sure they still have a strong password.

**Comment by faburem** [comment]
Hi,
thanks a lot for your great work on this. I have already merged your PR and released this change as version 0.89.6!
Is it okay for you if you use your documentation in the official titra wiki? We would of course attribute it to your github handle.

Best,
Fabian

**Comment by iamscottcab** [comment]
Yeah not a problem that's what open source is all about! Thanks for the quick turn around on the PR's, I'll check the docker container when it's on Docker Hub as the one there at the moment is a few days old. If you're accepting feature requests I added #163 just now to support the OIDC workflow for logging in / signing up :)

**Comment by faburem** [comment]
release in titra version 0.89.6 (this time for real 🥳)

**Comment by iamscottcab** [comment]
Fix confirmed in latest docker image. Thanks for the great support and product!
