### ISSUE TITLE
Favicon change on time tracker running?

### ISSUE THREAD

**Issue by Julianoe** [kromitgmbh/titra#159]
In the same vein as https://github.com/kromitgmbh/titra/issues/153 what if the favicon changed? I noticed that some other apps like Discord, Twitter or else have this trick so that info is displayed even when a lot of tabs are open or the tab is pinned
The user will always know if the tracker is running or not from a small peak at the corner of the screen.
![Capture d’écran_2023-03-03_14-01-42](https://user-images.githubusercontent.com/7274491/222727503-e5e3aee4-037a-4e57-aa68-358bb2455d22.png)
![Capture d’écran_2023-03-03_14-02-37](https://user-images.githubusercontent.com/7274491/222727508-29eb66ef-db9b-4ac3-9ba0-2ab47904a899.png)

![favicon-16x16-rec](https://user-images.githubusercontent.com/7274491/222727529-05dd6aeb-122a-43dc-a3ad-41c1983ca998.png)
![favicon-32x32-rec](https://user-images.githubusercontent.com/7274491/222727533-aedd2aec-62ab-48cf-a2ac-0000777a6495.png)

**Comment by faburem** [comment]
love the idea! Will put it in our backlog

**Comment by faburem** [comment]
Shipped with titra version 0.89.7!

**Comment by Julianoe** [comment]
Awesome ! I'll go read your code to see how I would have been supposed to do it "clean". I managed to demo it before creating the issue but it was dirty code 👍
Thanks for implementing it. I'm pretty sure lots of other freelance will benefit from it !

**Comment by faburem** [comment]
You're more than welcome! The best thing you can do for this project is to provide feedback like this and spread the word. 💪✌️
