### ISSUE TITLE
Use time zones when determining the preselected date on the "track time" page

### ISSUE THREAD

**Issue by lf-** [kromitgmbh/titra#16]
Hi! It seems like the date selected on the "track time" page of Titra is not taking into account timezones. More specifically, when I open the app, it is selecting Saturday when it is Friday here in UTC-8. 
![image](https://user-images.githubusercontent.com/6652840/83935951-74bf6780-a773-11ea-9bdd-4b72d4d7b2ba.png)

My server container *is* in UTC and that is probably what's showing through, but it would be helpful for distributed teams to have the time zone be per-user or potentially grabbed from the client.

Versions:
titra: 0.22.1
Node.js: 12.16.3
Meteor.js: 1.10.2
MongoDB: 4.2.7
Host environment:
Operating system: Linux (x64)
Uptime: 4 Minutes
Total memory: 3 GB
Free memory: 431 MB

**Comment by faburem** [comment]
Interesting find. Technically we are converting everything to UTC on the server side and convert it to the user timezone on the client already. Maybe we have missed something somewhere or this is not working for all scenarios. I will setup an environment with your specifications next week and see if we can reproduce the reported issue on our side. I'll keep you posted here.

**Comment by lf-** [comment]
I can confirm that the latest version fixes this. Thanks!

**Comment by faburem** [comment]
Thanks for your confirmation!
