### ISSUE TITLE
Changing start-times afterwards does not work

### ISSUE THREAD

**Issue by galaxyrun** [kromitgmbh/titra#160]
```
Versions:
    titra: 0.86.0
    Node.js: 14.21.2
    Meteor.js: 2.10.0
    MongoDB: 5.0.14

Server Environment:
    Operating system: Linux (x64)
    Runtime: 2 hours, 39 minutes
    Total memory: 15 GB
    Free working memory: 9 GB
```

If I enter the start time at 08:00, but later want to change it to 10:00, the software writes something completely different. In the attachment I have linked a sequence of pictures with my steps.

![1](https://user-images.githubusercontent.com/76906352/222904377-42181c4c-4ac4-4f6f-a65c-065f8a7f5f54.PNG)
![2](https://user-images.githubusercontent.com/76906352/222904470-d381488b-c023-4235-a0ac-ea31f7802823.PNG)
![3](https://user-images.githubusercontent.com/76906352/222904471-d52fea0d-168d-417c-a965-785d9370e905.PNG)
![4](https://user-images.githubusercontent.com/76906352/222904569-ebd0d333-952c-4a6f-8a44-183fb3f84a04.PNG)

**Comment by faburem** [comment]
Thanks for reporting this issue - it is fixed in titra version 0.89.5 which is being built and pushed to Docker hub right now.

Best,
Fabian

**Comment by galaxyrun** [comment]
Sorry for the newbie question, but what is the best way to update this without losing my data? (docker)

**Comment by faburem** [comment]
Basically you have to re-create the container so depending on how you deployed it initially you have to adjust the last run command to use your environment specific settings:
`docker pull kromit/titra && docker stop <titra-container-id> && docker rm <titra-container-id> && docker run <your-titra-settings>kromit/titra`
As an alternative you can also look at [Watchtower](https://github.com/containrrr/watchtower) which is automating the update process for you!
