### ISSUE TITLE
Calendar view in "Week" tab disappeared

### ISSUE THREAD

**Issue by galaxyrun** [kromitgmbh/titra#161]
```
Versions:
titra: 0.89.5
Node.js: 14.21.3
Meteor.js: 2.10.0
MongoDB: 5.0.14

Server Environment:
Operating system: Linux (x64)
Runtime: 117 minutes
Total memory: 15 GB
Free working memory: 10 GB
```

In the latest version, unfortunately, the calendar view "week" has disappeared. Mostly only Σ is displayed. A picture of this is attached (names have been censored on the left).

![week_bug](https://user-images.githubusercontent.com/76906352/222963489-6f27fca6-f8a8-4814-bcfd-6d83f4490c08.png)

**Comment by faburem** [comment]
Sorry but I'm not sure if I understand the "issue" here. The lines are collapsed by default and can be unfolded using the chevron icon. I don't think this is something we introduced recently but maybe we can do better at indicating this behavior through a hover animation? We could also add a setting to not collapse this view by default but based on experience this can get pretty crowded if you are tracking lots of different tasks.

**Comment by galaxyrun** [comment]
Sorry for opening the issue, I misunderstood something. I thought there was a calendar view with the week view just like with month.
