### ISSUE TITLE
Date sorting of details not working correctly in german format

### ISSUE THREAD

**Issue by John-H-Smith** [kromitgmbh/titra#164]
While viewing the details, I might want to order the rows by date.
But only the first numbers (day) is being considered by the sorting algorithm when the date is in the german language format (DD.MM.YYYY).
Instead, I would assume that the sorting for a date is considered first for the year, then the month, and then the day.
For this column might be useful to rewrite the sorting algorithm.

**Comment by faburem** [comment]
fixed in titra version 0.90.2! The problem was the client side sorting which was applied, this view is sorted on the server side though for performance reasons so this applied sorting was useless anyway and has thus been disabled in the latest version.

**Comment by John-H-Smith** [comment]
Nice, thank you!
