### ISSUE TITLE
Missing Email Setup Instructions

### ISSUE THREAD

**Issue by ColinTheBossReal** [kromitgmbh/titra#166]
Can you please add to your documentation the way the email work or how to setup your own SMTP?

**Comment by faburem** [comment]
This information was already available in the wiki but a bit hidden between other unrelated topics so I have just extracted everything into a dedicated page:
https://wiki.titra.io/books/deployment/page/sending-e-mails

Thanks for your feedback!

**Comment by faburem** [comment]
If you are missing anything please feel free to re-open this or create a new issue.
