### ISSUE TITLE
titra as PWA

### ISSUE THREAD

**Issue by ChrisB85** [kromitgmbh/titra#17]
Hi,
Firstly, thanks for great piece of software! :)
Secondly I would like to ask if there is a plan to make titra working as Progressive Web App? It would be nice to have it installed on desktop and running as separate process.

**Comment by faburem** [comment]
Thanks for your nice feedback! I have added PWA support to our [roadmap](https://github.com/kromitgmbh/titra/projects/1#card-39615688). There is not a lot left todo so expect it to ship soon.

**Comment by ChrisB85** [comment]
Great! Looking forward to it! :)

**Comment by ChrisB85** [comment]
Works great, thank you! :)
