### ISSUE TITLE
OpenID with GitLab.

### ISSUE THREAD

**Issue by Rishats** [kromitgmbh/titra#171]
Hello! 🤝

Have you tried working with the GitLab application?

I have created an application in self-hosted gitlab.example.com with the following scope:

- api 
- read_api
-  read_user 
- openid 
- profile 
- email

![image](https://user-images.githubusercontent.com/21194702/233640144-07022c20-20a1-4437-a17d-8a9b0459e7dd.png)

**I filled in all the data in the Admin Panel for Titra.**
![Screenshot from 2023-04-21 19-00-02](https://user-images.githubusercontent.com/21194702/233642301-a2313d88-60a2-4239-9b96-7b04a8927bc9.png)

When I try to authenticate, I get an error in the Titra logs:
`{"line":"406","file":"oauth_server.js","message":"Error in OAuth Server: Failed to fetch userinfo from OIDC https://gitlab.example.com/api/v4/user: failed [403] {\"error\":\"insufficient_scope\",\"error_description\":\"The request requires higher privileges than provided by the access token.\",\"scope\":\"read_user api read_api\"}","time":{"$date":1682080518485},"level":"warn"}`

🤔  Do I need to work with ID Token Fields? In Wekan, I map some data as environment variables and all work fine.

**Comment by faburem** [comment]
thanks for the hint about the scope! I think I have identified the culprit and just pushed a change which should allow you to fix the issue.
In fact, the scope was not missing from titra's request, but we were probably requesting more than needed:
`'openid', 'profile', 'email'`
If you update to titra version 0.92.1 you will see a new parameter in the OIDC Connect configuration screen (Request Permissions) which allows you to specify which permissions titra should request, if you just enter openid there it should fix the issue described. Unfortunately I cannot test it myself so I am looking forward to your feedback!
<img width="1340" alt="image" src="https://user-images.githubusercontent.com/11456790/234268695-bf7a7bc8-7e10-4b5a-92a6-f320a414e1c9.png">

**Comment by iamscottcab** [comment]
I'd double check that in GitLab you have the authorization mode for your application set to **Authorization Code** and that the ID of the generated application matches what you've pasted into Titra (along with secret which you need to paste in any time you make a change on that administration key).

That error is telling you it cannot find the application you've configured or the authentication method is not supported.

**Comment by faburem** [comment]
Thanks for your valuable feedback! With your permission I would add this information to the official titra wiki (with the proper credits of course).

**Comment by faburem** [comment]
Thanks for your input everyone, I have just added this information to the official titra wiki here:
https://wiki.titra.io/books/deployment/page/openid-connect-oidc-authentication

I am thus closing this issue as resolved 🕺
