### ISSUE TITLE
"Billing" status UI improvement: show that it is possible to edit the billing status from table

### ISSUE THREAD

**Issue by Julianoe** [kromitgmbh/titra#176]
Currently there is (I think) no UI indication that you can interact with billing status cell in the Details table.
It's even more difficult to guess it because no other cell in interactive, and it takes 3 clicks to activate the select form.

What about a small double arrow that is very light and becomes darker on hover? or something like that...
Also is it really necessary to make it so that 3 clicks are needed to edit the cell? why not just one?

![titra-avant-Capture d’écran_2023-05-25_02-46-51](https://github.com/kromitgmbh/titra/assets/7274491/d02b51c8-b8bd-4b00-9e6e-25df7759b1cb)

![titra-apres-Capture d’écran_2023-05-25_02-46-51](https://github.com/kromitgmbh/titra/assets/7274491/c901602f-73e7-47eb-ba19-114e5cfa61d9)

**Comment by faburem** [comment]
Added to our roadmap! Thanks for your feedback and the detailed suggestion!

**Comment by faburem** [comment]
I think I found a great solution for this:
- we are adding a chevron down icon in the table cell
<img width="1050" alt="Screenshot 2023-05-30 at 19 15 18" src="https://github.com/kromitgmbh/titra/assets/11456790/5824bf25-7157-43da-97eb-f10f6d874829">

- on click we are automatically expanding the dropdown behind the scenes:
<img width="1049" alt="Screenshot 2023-05-30 at 19 15 24" src="https://github.com/kromitgmbh/titra/assets/11456790/a5b35a2a-5398-43f0-9e94-759d64149386">

- on selection we are hiding everything again

this will ship with the next minor version of titra!

**Comment by Julianoe** [comment]
That looks great and way more intuitive! Love to see it!

**Comment by faburem** [comment]
this has just shipped in titra version 0.93.1 🎉 
Feel free to re-open or create a new issue if you experience any problems.
