### ISSUE TITLE
AGPL instead of GPL?

### ISSUE THREAD

**Issue by 12people** [kromitgmbh/titra#178]
AGPL seems like a more pertinent license, as it's just like GPL, but with the extra condition of not allowing others to host a server version of the code without contributing anything back. (The problem with the GPL is that it requires sharing code only for things that run locally on one's computer. As such, it is not recommended for server-side projects.)

If you don't want closed-source projects copying your back-end and just putting their own proprietary front-end on top of it without contributing anything back, it'd be good to switch to the AGPL.

**Comment by faburem** [comment]
Thanks for this suggestion, I will definitely consider changing the license!
