### ISSUE TITLE
Workingtime in minutes

### ISSUE THREAD

**Issue by ido1990** [kromitgmbh/titra#18]
Hi,
Thank you for this useful project, so convenient!
I wonder if it's possible to type in minutes inside the Workingtime on the tracking page.
I always get confused with the fractional numbers because sometimes I need to manually type the time for a phone call so I'm not using the built-in tracker.
When it's 1 hours or 1.5 hours it's easy but when I want to enter 5 minutes it's get confusing.
Hope I explained it well :)
Thanks!

**Comment by faburem** [comment]
Sorry I forgot to tag this issue, but it just shipped in titra version [0.24.0](https://github.com/kromitgmbh/titra/releases/tag/0.24.0).
It is currently being built on Docker hub so stay tuned 🕺

**Comment by ido1990** [comment]
That was quick, thank you!
I'm using the app.titra.io I hope it won't take long until they upgrade as well.
