### ISSUE TITLE
Details View Dates Are Off by One Day

### ISSUE THREAD

**Issue by CaptainPackers** [kromitgmbh/titra#182]
The dates of items in the Details View are all a day early. I looked through all the settings for a time zone setting but could not find one. Can you please look into this? Thanks.

**Comment by faburem** [comment]
The way we deal with timezones in titra is that we are converting all dates to UTC, which is what we store in the backend. When we display date/time information we display it in the local timezone based on the browser setting. I will check if we missed such a conversion anywhere.

**Comment by faburem** [comment]
quick follow-up question - are your referring to the Detailed, Daily, Working time tab or all of them are showing the wrong date?
Because I did find some missing utc conversions on the daily and working time tabs.

Thanks for your feedback!

**Comment by faburem** [comment]
Can you please let me know which timezone you are in and if your server and client are in different timezones?
I am trying to reproduce this issue but haven't been successful so far.

**Comment by faburem** [comment]
Never mind - I figured it out. This seems to be a bug in the date library dayjs we are using behind the scenes (https://github.com/iamkun/dayjs/issues/1284). Luckily there are many workarounds described since this seems to be a known issue.
Will be fixed in the next titra release!

**Comment by CaptainPackers** [comment]
Thanks

Regards,
Captain--
Sent with Tutanota, enjoy secure & ad-free emails.



Aug 10, 2023, 8:09 AM by ***@***.***:

**Comment by faburem** [comment]
this should be fixed in the latest titra version 0.94.4. Can you please confirm so we can close this issue?

Thanks!

**Comment by CaptainPackers** [comment]
Confirmed. Please close this issue. Thank you. I love this app and appreciate your support.

Regards,
Captain Packers--
Sent with Tutanota, enjoy secure & ad-free emails.



Aug 19, 2023, 9:05 AM by ***@***.***:

**Comment by faburem** [comment]
You're very welcome, thanks for your kind feedback!
