### ISSUE TITLE
Update old docker version

### ISSUE THREAD

**Issue by galaxyrun** [kromitgmbh/titra#185]
I've noticed that when I run `curl -L https://raw.githubusercontent.com/kromitgmbh/titra/master/docker-compose-auto-update.yml | ROOT_URL=http://localhost:3000 docker-compose -f - up`, it still installs version `0.89.5`. The latest version appears to be `0.95.3` according to GitHub. Could you please update it?

FYI: It doesn't seem to make a difference whether I use the Docker Compose file with or without Watchtower.

```
Versions
titra: 0.89.5
Node.js: 14.21.3
Meteor.js: 2.10.0
MongoDB: 5.0.14
Host environment
Operating system: Linux (x64)
Uptime: 9 Minutes
Total memory: 15 GB
Free memory: 10 GB
```

**Comment by faburem** [comment]
Hello,
please see the dedicated wiki page about how to update an existing installation:
https://wiki.titra.io/books/deployment/page/update-an-existing-titra-instance-docker

Best,
Fabian
