### ISSUE TITLE
Buggy saving

### ISSUE THREAD

**Issue by John-H-Smith** [kromitgmbh/titra#186]
When adding a new time and setting "1.1" as worked time, it will only add the time correctly when using ENTER to save. When clicking the "save" button, the time sometimes stays empty or resets to 0.00.
Same with the german format "1,1".

**Comment by faburem** [comment]
Unfortunately I cannot reproduce the issue. Can you please provide some sort of screen capture, especially with the developer tools console visible so I can check for any errors there.

Thanks!

**Comment by John-H-Smith** [comment]
Alright, here you go: https://ufile.io/i5ss215y

**Comment by faburem** [comment]
got it, thanks! That actually helped a lot already to better understand the issue.

**Comment by faburem** [comment]
FYI, this was caused by the rounding feature - it should work properly now!
