### ISSUE TITLE
Modification of source code files

### ISSUE THREAD

**Issue by WinDino** [kromitgmbh/titra#188]
Hello,
I want to modify the file imports/ui/pages/overview/projectlist.html. However, in the container (`/app/bundle/programs/web.browser/dynamic/imports/ui/pages/overview/projectlist.html`), the content is: 

`function module(t, e, l) { l.link("./template.projectlist.js", {"": "+"})}.`

How can I access the actual HTML file of the page and ensure that the modifications take effect?
Do I need to create a new docker image? How do I go about it?

Thanks in advance.

**Comment by faburem** [comment]
Hello,
the way to go is to checkout the source code from git, make modifications to the source code and then compile a custom docker image using `docker build -t yourdockerimagename`. You can then either push that image to Docker hub to use it on a remote server or build it directly on the server and use it straight away.

I hope this helps,
Fabian

**Comment by WinDino** [comment]
Hello,
Sorry for my delayed response, I encountered several issues with this.
Thank you, it helped me.
