### ISSUE TITLE
Wekan integration in Docker environment

### ISSUE THREAD

**Issue by revis3d** [kromitgmbh/titra#19]
We have wekan and titra running in docker containers on the same host. When trying to add the wekan integration address in project settings the URL is never accepted. Any idea how to make it work?

**Comment by faburem** [comment]
Have you set the correct [CORS settings](https://github.com/wekan/wekan/blob/1617577378fc17ca09fd3ef34f24e02c2889aa9f/docker-compose.yml#L295-L301) in your wekan container?
We are setting it as follows through environment variables in our testing environments:
- CORS=*
- CORS_ALLOW_HEADERS=Authorization

**Comment by revis3d** [comment]
That did the trick. Thank you.

**Comment by faburem** [comment]
sure thing, I will review our documentation and make sure to make this more clear
