### ISSUE TITLE
Stopwatch Toast Persists

### ISSUE THREAD

**Issue by CaptainPackers** [kromitgmbh/titra#190]
When I use the stopwatch, the "toast" pop up message persists and does not disappear as it should, and it is kind of in the way. Can you please look at this?

![image](https://github.com/kromitgmbh/titra/assets/7439853/e5cf3061-0a75-4986-b70b-5e90243365f9)

**Comment by faburem** [comment]
should be fixed in titra version 0.95.7!

**Comment by CaptainPackers** [comment]
Looks good! Thanks for the quick response!
