### ISSUE TITLE
When creating a time record a new task record is created with same title

### ISSUE THREAD

**Issue by helioguardabaxo** [kromitgmbh/titra#191]
Steps to reproduce:
1 - Create project "My **first** project" and create tasks "Task 01" and "Task 02"
2 - Create project "My **second** project" and create tasks "Task 03" and "Task 04"

In this moment, mongo database show only tasks created on Tasks collection:
![Captura de tela de 2023-12-12 08-42-31](https://github.com/kromitgmbh/titra/assets/24301085/38924911-cc1b-496a-b29b-a3fe0f57ab0e)

3 - Create a "track time" for "My first project" using "Task 01"
Now, mongo database create record on Timecards collection:
![Captura de tela de 2023-12-12 08-45-27](https://github.com/kromitgmbh/titra/assets/24301085/7b44b572-130a-4c95-8e4b-0c0631b46f7f)

But create a wrong record on Tasks collection:
![Captura de tela de 2023-12-12 08-44-46](https://github.com/kromitgmbh/titra/assets/24301085/1cb6d9b3-8fb3-4a58-8f94-fb2ee1025dc2)

This wrong record is showed for all projects:
![Screenshot 2023-12-12 at 08-44-07 titra - track time](https://github.com/kromitgmbh/titra/assets/24301085/030700c8-7824-4244-9001-9b294ce06efa)

![Captura de tela de 2023-12-12 08-59-53](https://github.com/kromitgmbh/titra/assets/24301085/02ea6eed-c712-4bfe-8d32-966a614a999c)

**Comment by faburem** [comment]
Thanks for the detailed report! Should be fixed in titra version 0.95.8 which is currently being built and pushed to Docker hub.
