### ISSUE TITLE
Text and background need more contrast on Administration page

### ISSUE THREAD

**Issue by helioguardabaxo** [kromitgmbh/titra#192]
Texts and background colors on tables:
![Screenshot 2023-12-12 at 10-19-39 titra - administration](https://github.com/kromitgmbh/titra/assets/24301085/7330d570-8a38-4370-8695-b5670c162050)

**Comment by faburem** [comment]
Fixed in titra version 0.95.9. There was an issue with our github actions which builds and pushes images to Docker hub, but it should be resolved now.
