### ISSUE TITLE
Tasks displayed on track time form

### ISSUE THREAD

**Issue by helioguardabaxo** [kromitgmbh/titra#193]
In a project I have 20 tasks.
When I try to create a tracktime just 10 entries are displayed and this list is unsorted.
"Number of tasks displayed in the task search" is set to 20
![Screenshot 2023-12-13 at 07-58-28 titra - track time](https://github.com/kromitgmbh/titra/assets/24301085/c8391afc-a1a9-4491-a0ee-b909aa1d65a9)

In "Tasks" popup I have the same problem with number of tasks displayed
![Screenshot 2023-12-13 at 07-58-53 titra - track time](https://github.com/kromitgmbh/titra/assets/24301085/176b82a1-8922-44ee-9476-1b5850c0d50d)

**Comment by faburem** [comment]
fixed in version 0.95.10
