### ISSUE TITLE
 Task date bar toast persists

### ISSUE THREAD

**Issue by helioguardabaxo** [kromitgmbh/titra#195]
This issue is similar #190 

When I click on a date bar, toast are displayed but do not have a way to close it.
![image](https://github.com/kromitgmbh/titra/assets/24301085/2db5afdf-a333-4d3d-af6d-cbbf5feb739d)

**Comment by faburem** [comment]
fixed in version 0.95.10, you can now click anywhere outside the toast to hide it.
