### ISSUE TITLE
Task list field is hidden when double clicked for edit

### ISSUE THREAD

**Issue by helioguardabaxo** [kromitgmbh/titra#196]
Task list:
![Screenshot 2023-12-13 at 08-23-54 titra - edit project](https://github.com/kromitgmbh/titra/assets/24301085/d781e2af-ff64-4369-a339-9cce45c67479)

After I clicked a task and edit it:
![Screenshot 2023-12-13 at 08-24-14 titra - edit project](https://github.com/kromitgmbh/titra/assets/24301085/0bea8fbf-6ac2-462b-8370-d55d8eef2df5)

If I click in other task, the hidden field are displayed.

**Comment by faburem** [comment]
fixed in version 0.95.10
