### ISSUE TITLE
No strings are shown.

### ISSUE THREAD

**Issue by mzch** [kromitgmbh/titra#20]
After updating to 0.24.0, no strings have become not to be shown in titra pages.

<img width="1497" alt="ScreenShot" src="https://user-images.githubusercontent.com/621178/84518507-c041ba80-ad0b-11ea-9d7e-27f66409816c.png">

What's wrong?

- Using Docker image

**Comment by faburem** [comment]
Should be fixed in version 0.24.1, sorry for any inconvenience this might have caused!

**Comment by mzch** [comment]
@faburem Fine! Thanks! :)
