### ISSUE TITLE
Concerns about Future Updates and MongoDB Version Compatibility

### ISSUE THREAD

**Issue by sondi2003** [kromitgmbh/titra#200]
In the current provided docker-compose.yml, MongoDB 5.0 is specified. However, MongoDB 5.0 requires AVX support, which is not supported by my NAS. Consequently, I've installed MongoDB 4.0, and everything is functioning correctly.

My concern is whether using MongoDB 4.0 might pose issues in the future. Can I proceed with future updates from Titra while keeping the database in the current version (MongoDB 4.0)? I want to ensure that updating Titra won't lead to any compatibility problems with MongoDB 4.0.

**Comment by faburem** [comment]
Hello and thanks for reaching out,
titra is built on Meteor.js which is in turn using the official Node.js MongoDB driver. The official statement regarding compatibility can be found [here](https://guide.meteor.com/2.6-migration#:~:text=You%20can%20check%20here%20which,%2C%204.2%2C%204.0%2C%203.6.).

titra will always be updated to the latest Meteor.js version and thus inherit its dependencies. If you are really stuck on version 4.0 that could indeed be a problem in the near future, however version 4.4 should be safe for at least another year according to the official statement from MongoDB about driver compatibility [here](https://www.mongodb.com/docs/drivers/node/current/compatibility/#:~:text=MongoDB%20ensures%20compatibility,Lifecycle%20Schedules.).

**Comment by faburem** [comment]
added this information to our [wiki](https://wiki.titra.io/books/deployment/page/mongodb-version-compatibility) for future reference.
