### ISSUE TITLE
Feature request: Add cost/hour for each member

### ISSUE THREAD

**Issue by Mr4013** [kromitgmbh/titra#203]
Hello,

Not sure if it has been suggested before, I didn't find it on the closed issues here.

It would be nice, apart from the cost/hour per project, that each member had a personal cost/hour, maybe visible only for administrators.

This way, it would be even faster to make the cost calculations when the data is exported to Excel.

**Comment by faburem** [comment]
Hi and thanks for reaching out,
this feature is available since titra version [0.94.3](https://github.com/kromitgmbh/titra/releases/tag/0.94.3):
<img width="1341" alt="image" src="https://github.com/kromitgmbh/titra/assets/11456790/13e5fad2-9b3f-4429-bebc-e7beb14922c4">
