### ISSUE TITLE
Day input in week view - moves input by one day

### ISSUE THREAD

**Issue by laliluna** [kromitgmbh/titra#204]
When adding a day in the week based input, the day is shifted by one day after saving.

Timezone on the server: Europe/Berlin
Version: docker  image 0.96.3
Beginning of week in settings is Monday 

When choosing Sunday as start, the day is shifted by two days.

Below you can find screenshots of the input and the database entry.

 
<img width="1106" alt="week-issue-after-saving" src="https://github.com/kromitgmbh/titra/assets/200958/d40799a6-f6e7-461e-af2f-d4e8a474094a">
<img width="434" alt="week-issue-db-screenshot" src="https://github.com/kromitgmbh/titra/assets/200958/b74e7373-e04f-417d-8eb1-f71ec78292a5">
<img width="1100" alt="week-issue-input" src="https://github.com/kromitgmbh/titra/assets/200958/1fe9f9d4-9792-414d-8528-5f2b6195c8d2">

**Comment by readtedium** [comment]
A related issue is that the holidays appear to be slightly off on the calendar as well.


![Screenshot from 2024-02-14 09-40-29](https://github.com/kromitgmbh/titra/assets/470216/27a04a86-76fe-49be-b2cd-81dcfeca9d8e)

(Great project by the way!)

**Comment by faburem** [comment]
should be completely fixed in titra version 0.96.6!

**Comment by laliluna** [comment]
Is fixed!
