### ISSUE TITLE
Bug: wrong time calculation when time unit is set to minutes 

### ISSUE THREAD

**Issue by RKLBusinessDevelopment** [kromitgmbh/titra#212]
I have set the time unit to minutes, when stopping the timer, the calculated time is not shown in minutes, which is incorrect and misleading.

To reproduce:
- set the time unit to minues
- start the timer, let it run for a bit more than  2 minutes and stop it
- the calculated time is "0.03".
![image](https://github.com/user-attachments/assets/da3effff-ef4f-426b-a4d6-538597633d79)
![image](https://github.com/user-attachments/assets/8ff68661-60a6-4eea-9f68-6a8ae61e171f)

**Comment by faburem** [comment]
should be fixed in titra version 0.98.2 - thanks for reporting this issue!

**Comment by RKLBusinessDevelopment** [comment]
I can confirm that the problem is fixed in the latest version. Thanks a lot for the very fast fix, much appreciated.
