### ISSUE TITLE
LDAP Authentication failed 

### ISSUE THREAD

**Issue by sondi2003** [kromitgmbh/titra#217]
Hello
I haven't needed my self-hosted version for a while now. I wanted to log in today, which always ended with the error "LDAP Authentication failed with provided username [test@test.ch] [LDAP-login-error]".
I then checked whether I was up to date.
mongo:6.0
kromit/titra:latest
I then reset my password. The email sent worked. The new password was accepted and I was able to add my entries. However, after I logged out again and tried to log in again, the same thing happened again:
"LDAP Authentication failed with provided username [test@test.ch] [LDAP-login-error]"
I don't use LDAP at all.
What else can I do?
Why doesn't it work anymore?
Actually, it's your standard dockercompose.yml
Many thanks
sondi2003

**Comment by zweimalk** [comment]
Got the same problem, titra:latest and mongo:5.0
There where I've got active session it is working, but no one can login

**Comment by zweimalk** [comment]
For what I understand, It is because ldap extension is now included in latest release? 
If so, how to disable?

**Comment by faburem** [comment]
My bad, this will of course be fixed ASAP! For the time being I think you can pass the environment variable LDAP_LOGIN_FALLBACK=false to fix the login!

**Comment by faburem** [comment]
this should be fixed in titra version 0.99.12. Please let me know if there are still any issues!

**Comment by sondi2003** [comment]
hello everyone,
thank you very much. now it works again for me.
the update helped
