### ISSUE TITLE
[Feature request] API to fetch time entries by date and project 

### ISSUE THREAD

**Issue by matfiz** [kromitgmbh/titra#218]
We're happily using Titra. Thanks for making a tool that does one thing and does it great!

We're looking for an option to automate the readout of time entries per project. I've explored the API. There's an endpoint to list projects. However, I miss an endpoint to fetch time entries between start_date and end_date for a given project_id (provided that I'm and admin). 

Do you have any plans to add such API?

**Comment by faburem** [comment]
That's a great idea! We will add this to our API.

**Comment by faburem** [comment]
shipped with titra version 0.99.13!

**Comment by faburem** [comment]
in fact, the version is 0.99.14 - I had to to another version bump due to a failed build..

**Comment by matfiz** [comment]
Thank you @faburem. Kudos ☕  and/or 🍻 to you!

**Comment by matfiz** [comment]
@faburem I've just given it a try. It works awesome, but it returns just time entries for my user. In my usecase, I need to read time entries for all users who report hours in the project. 

Any chance on extending the API further? 🥺

**Comment by faburem** [comment]
I guess that makes sense, but we should do it for all API endpoints then. I will add it to our backlog!

**Comment by faburem** [comment]
I have added two new API endpoints:
- /project/timeentries/
- /project/timeentriesfordaterange/

for me this is the only reasonable way to implement this without exposing too much information through the API. For your particular use case you might have to fetch the list of projects first (/project/list) to get the projectID which you then have to provide for the two new API endpoints.

I hope this helps!

**Comment by matfiz** [comment]
@faburem This is exactly what I needed 🥇  Thank you so much, you rock 🎸
