### ISSUE TITLE
API Documentation Missing

### ISSUE THREAD

**Issue by gatkramp** [kromitgmbh/titra#22]
I can see there is a build API, and in Titra I see that I can generate API token, but there is no documentation that I am aware of regarding the use of the API. Would love to build custom integrations between Titra and Wekan.

**Comment by faburem** [comment]
indeed this was missed when we migrated the wiki 😇
it's actually still available at [https://kromitgmbh.github.io/titra/](https://kromitgmbh.github.io/titra/) but we accidentally removed all links there 🤷‍♂️

**Comment by gatkramp** [comment]
Fantastic. This is exactly what I am looking for. Thank you very much.
