### ISSUE TITLE
API documentation typo for TimeEntry | Get time entries for daterange

### ISSUE THREAD

**Issue by ed-parsadanyan** [kromitgmbh/titra#220]
![image](https://github.com/user-attachments/assets/e5822253-4359-4108-9929-5646b66ef634)

`/timeentry/list/daterange/:fromDate/:toDate` seems to be a typo and `/timeentry/daterange/:fromDate/:toDate` should be instead

https://github.com/kromitgmbh/titra/blob/c421890c50c3518ee720a7e73206de8ad9336bb9/server/APIroutes.js#L153-L172

**Comment by faburem** [comment]
thanks for reporting this, it should be corrected now - you might have to hard refresh the API docs page.
