### ISSUE TITLE
[bug] Stopwatch doesn't save hours if a time greater than an hour is tracked

### ISSUE THREAD

**Issue by w-lfchen** [kromitgmbh/titra#221]
v0.99.19, using the Dockerfile.

## Steps to reproduce

1. Set display time to minutes
2. Track time using stopwatch
3. Let the stopwatch run for more than an hour
4. Stop the stopwatch
5. Only the minutes will be transferred into the `working time` field

**Comment by faburem** [comment]
bug fix shipped with v0.99.20!

**Comment by w-lfchen** [comment]
thank you so much for the quick response! :heart:
