### ISSUE TITLE
Connecting to external database

### ISSUE THREAD

**Issue by ido1990** [kromitgmbh/titra#23]
Hi,
I'm running the docker image and I wonder if it's possible to use external MongoDB cluster.
I've free cluster on MongoDB Atlas but when I changed the URL for MongoDB on Titra, it crashed.
[Atlas](https://www.mongodb.com/cloud/atlas)
Thanks!

**Comment by faburem** [comment]
Hi,
yes this should work. Titra is built using the Meteor.js framework so you can follow any guides available for it. I found this one [https://medium.com/@cfnelson/mongodb-atlas-with-meteor-a-step-by-step-guide-da34093665f4](https://medium.com/@cfnelson/mongodb-atlas-with-meteor-a-step-by-step-guide-da34093665f4). While maybe a little bit out-dated it should at least cover the essentials.

Please let me know if it worked and how we can document it for future users!

Thanks

**Comment by ido1990** [comment]
Found it.
In MongoDB Atlas, you click the connect button and then choose the **Node.js** driver and **2.2.12 or later** as version.
It seems like Meteor doesn't work with "mongodb+srv://" and the connection string isn't recognized.
The correct one is:
`mongodb://<username>:<password>@<server1>.mongodb.net:27017,<server2>.mongodb.net:27017,<server3>.mongodb.net:27017/<dbname>?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true&w=majority`
