### ISSUE TITLE
Incorrect Table Styling

### ISSUE THREAD

**Issue by gatkramp** [kromitgmbh/titra#24]
Hello 

I have a issue where the table in the details page is not correctly styled. Please see below images for more information:

**Current Config**
![image](https://user-images.githubusercontent.com/8925826/86367700-9598b100-bc7c-11ea-80b9-f5178c2634b1.png)

**Current Project**
![image](https://user-images.githubusercontent.com/8925826/86368009-fde79280-bc7c-11ea-9c90-f4cabf8e065a.png)

**Error Replication**
**Step 1**
Click on the "Details" page
![image](https://user-images.githubusercontent.com/8925826/86368229-3d15e380-bc7d-11ea-97d9-917948c7a217.png)

**Step 2**
Click on a tab with a empty result, in my case "Total" Tab:
![image](https://user-images.githubusercontent.com/8925826/86368400-6afb2800-bc7d-11ea-8d07-2dbc3f2ab621.png)

**Step 3**
Any other tab with information showing will now be incorrectly styled, eg "Detailed" tabs.
![image](https://user-images.githubusercontent.com/8925826/86368860-feccf400-bc7d-11ea-8db7-4b2c342e5fb4.png)

**Step 4**
Sometimes, a fix for the styling is just to change the Filter and the styling appears correctly again:
![image](https://user-images.githubusercontent.com/8925826/86369507-d5609800-bc7e-11ea-8a57-dcd221e0e4a9.png)

Forgive my lack of incorrect terminology.

**Comment by faburem** [comment]
Wow! Thanks for the detailed report 🤓
We do see this issue as well occasionally but are not able to pin down a reproduction scenario yet. It seems to be some kind of timing issue when loading resources from the server, we will do some more investigation and keep this issue updated with any news.

**Comment by centralhardware** [comment]
I have the same problem, what information about the system can be useful?

**Comment by faburem** [comment]
I cannot reproduce this issue any more in the latest version of titra. If you still encounter it feel free to re-open this issue.

Thanks,
Fabian
