### ISSUE TITLE
API not working

### ISSUE THREAD

**Issue by gatkramp** [kromitgmbh/titra#26]
Hello

I have been trying to use the API with no avail.

I am testing using the documentation, with my local server giving the same result.
![image](https://user-images.githubusercontent.com/8925826/87782239-7419f680-c832-11ea-88f3-4a7c117b07a5.png)

I create a API token on the app.titra.io website under the user settings. 

I use the same API token, but it gives me the error above.

Is the API working?

**Comment by faburem** [comment]
Hi,
yes the API is working. There are just two things to consider:

1. there was a typo in the API documentation which I just fixed - the path is project/list, project/create and so on (not projects)
2. for whatever reason the apidoc sample request functionality is not working anymore because it is not correctly sending the required authorization header to the API endpoint. Unfortunately I was not able to find a quick fix for this, however you can use any API testing tool to verify the API (I am using AdvancedRestClient) here:
<img width="1402" alt="Screenshot 2020-07-17 at 18 34 36" src="https://user-images.githubusercontent.com/11456790/87809945-801aae00-c85c-11ea-8116-5492d071c3e8.png">

**Comment by gatkramp** [comment]
For fear of losing my sanity, can you please assist me? After the info provided above, I ran the following:

In python 3.7.3
```
import requests
titra_key = "fxCjcT7tPZbCaTc2X"
HEAD = {"Authorization": "Bearer "+titra_key}
URL = 'http://localhost:3050/project/list/'
session = requests.Session()
s = session.get(URL,headers=HEAD)
s.json()
```
which gives me a working result:
```
{'statusCode': 200,
 'message': 'Returning projects',
 'payload': [{'_id': 'KLBAXZzaieYSroC2q',
   'name': 'Projects',
   'color': '#8563F9',
   'customer': '',
   'notbillable': True,
   'wekanurl': 'http://localhost:8001/api/boards/Keqcn4r33M3fvMsGX/export?authToken=EvW4vZrAw1OWF7ocAYGauX6lB4ZRX3RCg3k4BfLPABi',
   'desc': '',
   'selectedWekanList': ['LzKBaxdQxXigJS9CG',
    'CuuhmKx8rLacupFC7',
    'yFNZ7WqZ4PhMmhkWX',
    'te68ukkkdL7rw2wvh',
    'doD5sbMnvhCqbAGWP',
    'nL5xuDMtxFkArsYg6',
    'bEv7voxYPYat4AAhj',
    'LKvQGGvQkkWEgNssn',
    't4mdwebkkHk3G3zD4',
    'xmT2Wp9LHD2T42weg',
    'Tp5sgGqkoPAA9mwK7'],
   'public': True,
   'userId': 'ZoNEzDTngRAF3n9AZ',
   'team': ['8yyppjuJ2gjWAG3qF']}]}
```
Then I try the following:
```
URL = 'http://localhost:3050/timeentry/create/'
PARAMS = { "projectID": "KLBAXZzaieYSroC2q",
         "task": "Test Task", 
         "date": "2019-11-10", 
         "hours": 8}
s = session.post(URL,params=PARAMS,headers=HEAD)
s.json()
```
Which gives me:
```
{'statusCode': 400, 'message': 'Invalid JSON received. Error: Invalid JSON'}
```
Do you know why that can possibly be happening?

**Comment by faburem** [comment]
Hi,
sorry for the late response. I just tried this on my local dev environment and found out that there was another typo in the API docs which I just corrected - the correct param is "projectId" and not "projectID".
My other assumption is that the parameters are not received as application/json, can you try to use this python library https://docs.python.org/3/library/json.html or apparently easier try this solution suggested on stackoverflow https://stackoverflow.com/questions/9733638/post-json-using-python-requests
I hope it works for you!

Best regards,
Fabian

**Comment by gatkramp** [comment]
I fixed the issue with your assistance. It was two fold. I changed the projectID to projectId and sent the information as json. Now it is working.

```
import requests, json
titra_key = "fxCjcT7tPZbCaTc2X"
URL = 'http://localhost:3050/timeentry/create/'
HEAD = {"Authorization": "Bearer "+titra_key}
PARAMS = { "projectID": "KLBAXZzaieYSroC2q",
         "task": "Test Task", 
         "date": "2019-11-10", 
         "hours": 8}
session = requests.Session()   
session.post(URL,json=PARAMS,headers=HEAD).json()
```

**Comment by faburem** [comment]
🤘
