### ISSUE TITLE
How to get Wekan URL?

### ISSUE THREAD

**Issue by freezurbern** [kromitgmbh/titra#27]
Wekan does not appear to have a valid URL when right clicking Export Board as the wiki suggests.

**Comment by faburem** [comment]
that's right, the Wekan UI has slightly changed. I have updated the wiki to reflect this change. There is now a new sub menu of the export board feature, just click on the menu item once and then right click on "Export board to JSON" to get the correct URL!
<img width="1077" alt="Screenshot 2020-07-17 at 18 25 06" src="https://user-images.githubusercontent.com/11456790/87809434-af7ceb00-c85b-11ea-8470-f543de544a6f.png">

**Comment by freezurbern** [comment]
Thanks! Another useful update to the wiki would be direct linking to the Wekan CORS settings like in issue #19  
https://github.com/wekan/wekan/blob/1617577378fc17ca09fd3ef34f24e02c2889aa9f/docker-compose.yml#L295-L301
