### ISSUE TITLE
Feature suggestion: Total of all days in week view

### ISSUE THREAD

**Issue by freezurbern** [kromitgmbh/titra#28]
I would like to suggest adding the weekly total to the week view. I'm not sure where best to put it, but I made a screenshot (total in red, censored in pink):
<img width="1046" alt="titra-week-total-suggestion" src="https://user-images.githubusercontent.com/6363417/87842547-342b3180-c87b-11ea-8b91-a531f895e427.png">

Thanks for such a useful and Docker friendly project. This has helped me manage my time across multiple projects while working from home.

**Comment by faburem** [comment]
Thanks for the suggestion, we will review it internally and keep you posted in this issue.

**Comment by faburem** [comment]
Approved. This feature suggestion has been added to our [roadmap](https://github.com/kromitgmbh/titra/projects/1#card-42216119).
