### ISSUE TITLE
Date format hints

### ISSUE THREAD

**Issue by freezurbern** [kromitgmbh/titra#29]
On the track and week pages, I would like the date to show as (for example) `Friday, July 17, 2020`. I'm unable to find any information in the wiki about the correct date format options to use in the /admin menu. Perhaps in the /admin menu, link to the relevant page (for PHP I am used to referring to https://www.php.net/manual/en/function.date.php for options)

**Comment by faburem** [comment]
Here is the information you are looking for about the [available date formats](https://day.js.org/docs/en/display/format). I will also add it to the wiki and try to find a place in the application to point to it.

**Comment by freezurbern** [comment]
I'm not sure if I should create a new issue for this, but titra does not store dates correctly after changing the date format. I set:

> ![titra-date-formats](https://user-images.githubusercontent.com/6363417/87998871-25d15580-cac7-11ea-95e9-3e57291879d1.png)

Then tried to add a new task and it didn't appear in the date selected:

> ![titra-date-1970](https://user-images.githubusercontent.com/6363417/87999030-a85a1500-cac7-11ea-9f57-78f05a1080c9.png)


To me it appears to be a parsing error.

**Comment by faburem** [comment]
please create a new issue and close this one so we can track it correctly.

Thanks!

**Comment by faburem** [comment]
Forgot to mention this in release 0.27.0, but we added a link to the wiki describing the globalsettings page so I am closing this issue now. As mentioned before, please open a new issue for the problem described above - thanks!
