### ISSUE TITLE
Any Wekan bridge?

### ISSUE THREAD

**Issue by gerroon** [kromitgmbh/titra#3]
Hi

You recommend Wekan as a companion. I am wondering if there is some kind of bridge between these apps.

**Comment by faburem** [comment]
Hi,
yes we have built an interface to retrieve cards from specific wekan board lists, it is documented in our wiki [here](https://github.com/kromitgmbh/titra/wiki/Wekan-integration). It might need some updates due to recent changes. If somethings not working do not hesitate to open an issue for it!

**Comment by faburem** [comment]
Added the wiki update to our roadmap https://github.com/kromitgmbh/titra/projects/1#card-30782094

**Comment by faburem** [comment]
The wiki has been updated to reflect the latest changes in titra. Closing the issue.
