### ISSUE TITLE
Start / Stop time tracking as well as duration

### ISSUE THREAD

**Issue by Geoffjnt** [kromitgmbh/titra#35]
Hi Fabian & team, 

I am very pleased with the Titra / Wekan combo, kudos for a good piece of software and integration.   Thank you.

I have since getting it working realised that there is no tracking of when the time was spent, which is unfortunately critical to me, so I submit the following user story for your consideration for roadmap inclusion:

[User Story]
As a user of Titra, on a TimeCard I need at a minimum to track and edit Start Time (editable) as well as duration,  
as our billing requires time start (nearest minute), time stop (nearest minute), duration (minutes).
(Right now, the date field stored in the timecards collection has 00:00:00.000+00:00 as the timestamp)
A very desirable feature would be a Stop Date/Timestamp field stored in the database,  
with the ability to EITHER enter a start time and stop time manually, to calculate duration  OR
enter start time and duration, calculating stop time (e.g. with the current timer populating duration). 

Perhaps revealing time fields in the timecard dialog could be based on an administrative option, to avoid overcomplicating things for users who don't need this feature.

Thanks again, and best regards, 

Geoff

**Comment by faburem** [comment]
This enhancement has been implemented, closing the issue.

**Comment by Geoffjnt** [comment]
Thank You!  I look forward to testing it.   Merry Yule!
