### ISSUE TITLE
[Help] Wekan integration — URL not valid

### ISSUE THREAD

**Issue by wangxu94** [kromitgmbh/titra#36]
**Titra version:** titra: 0.32.0
**Host:** Docker on Ubuntu 18.04

I tried to set up Wekan integration following the instructions [here](https://github.com/kromitgmbh/titra/wiki/Wekan-integration). However, when I click "Check", I get an exclamation mark. I am able to access the URL from both my desktop computer and the server that is running titra. 

The docker container logs do not show anything useful.

Please let me know if you need any additional information. Any help would be much appreciated.

Thank you.

**Comment by faburem** [comment]
Hi,
can you please share a screenshot and/or the url so we can better help you with your issue?

Thanks,
Fabian

**Comment by wangxu94** [comment]
Hi, thanks for replying. 

The URL is: https://wekan.xwang.pw/api/boards/EEDcrz3GqExittBFo/export?authToken=ez3A5gSOIJ3AjuSxe3oCwgocwaDdekmgW1FzPxfF2HJ

Wekan screenshot:
![image](https://user-images.githubusercontent.com/15028233/100284113-8b80a180-2fd3-11eb-8f80-eaf736cf554f.png)

Titra screenshot:
![image](https://user-images.githubusercontent.com/15028233/100284069-7572e100-2fd3-11eb-9ef2-a52926b5e1f7.png)
