### ISSUE TITLE
custom fields for track record

### ISSUE THREAD

**Issue by centralhardware** [kromitgmbh/titra#38]
It would be useful for store some additional information about task that cannot be restored from the name of task, and the data will already be forgotten from memory

**Comment by faburem** [comment]
thanks for your feedback, we will discuss this in our next stand up meeting and decide if we put it on our roadmap.

**Comment by awokurka** [comment]
This would be indeed very nice to have. In my case i want to account time based on tickets fetched from Zammad.  In Zammad a Ticket consists of many articles but you can only account time for the Ticket as a whole, missing important information for billing (what was done when). I think that titra could fill this gap very easily by supporting some custom text/string fields and a date/time picker in task records.  

A possible workflow can be:
Record time -> search and pick ticket from zammad -> pick start time -> enter short description like 'phonecall with jane doe' -> 0.25 hours -> after office hours? (yes/no) -> save.

For billing we could just export the time from tintra and attach a spreadsheet containing the ticket numbers from zammad for the billing period.

**Comment by faburem** [comment]
thanks for your feedback - that seems to be a really good use case!
It is already on our roadmap, I will bump the priority on it.

**Comment by awokurka** [comment]
This is great! Thank you very much.

**Comment by faburem** [comment]
This feature has shipped in titra version 0.54.0 💪
![image](https://user-images.githubusercontent.com/11456790/126871064-2731fcb3-e680-444b-8f65-a256864354a9.png)
Feel free to open another issue if you encounter any problems!
