### ISSUE TITLE
mission css styles when open direct via ip and port

### ISSUE THREAD

**Issue by centralhardware** [kromitgmbh/titra#39]
![image](https://user-images.githubusercontent.com/26829359/102045063-bb6cd900-3e0a-11eb-9460-abadc8a3c291.png)

note: ROOT_URL is set

**Comment by faburem** [comment]
Can you please post a screenshot / content of your browsers developer console? Otherwise it is impossible for us to help!

Thanks,
Fabian

**Comment by centralhardware** [comment]
server logs look like
````
[ERROR: [ostrio:flow-router-extra] [route.wait] Promise not resolved @ Tue Dec 15 2020 11:57:24 GMT+0000 (Coordinated Universal Time)] { 
   "browserInfo": { 
     "browser": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36", 
     "userId": null, 
     "url": "http://server.home:3333/", 
     "resolution": "1920x1080" 
   }, 
   "stack": {} 
 } 
````

dev tool log

![image](https://user-images.githubusercontent.com/26829359/102212403-bccffb80-3f07-11eb-8862-7bdb26575546.png)

**Comment by centralhardware** [comment]
titra try to fetch data by ROOT_URL, but request fail with

![image](https://user-images.githubusercontent.com/26829359/102213481-5f3cae80-3f09-11eb-95a5-3e8697205905.png)

**Comment by faburem** [comment]
What is the ROOT_URL set to? It looks like it is different than the URL you are entering in the browser.

**Comment by centralhardware** [comment]
ROOT_SET is a domain look like titra.example.com, but i try to open via server ip address and exposed port, some time i have my reverse proxy issue and in this case i use direct access

**Comment by faburem** [comment]
I think this scenario is prevented by modern browser's security policies. You have to access titra through the URL defined as ROOT_URL. Because I don't see how we could fix this on the titra application side I would close this issue. It sounds like this is more related to your reverse proxy setup.
