### ISSUE TITLE
Default admin user/pass?

### ISSUE THREAD

**Issue by gerroon** [kromitgmbh/titra#4]
Hi

I just deployed with docker but I am not sure what the default user/pass  is. Is there such defaults? I cant find that in the wiki either, neither in the compose file.

thanks

**Comment by faburem** [comment]
Hi,
there is currently no admin page because all settings are use specific. However, dedicated global administration settings are on our roadmap, you can follow the progress here: https://github.com/kromitgmbh/titra/projects/1#card-30267825

**Comment by faburem** [comment]
The administration page has been delivered in titra version [0.9.9](https://github.com/kromitgmbh/titra/releases/tag/0.9.9). Please refer to our shiny new [wiki](https://titra.io/en/wiki/category/administration/) on how to get started.
