### ISSUE TITLE
Initial hint for tasks

### ISSUE THREAD

**Issue by nikolay-martynov** [kromitgmbh/titra#42]
When you have integration with Wekan, you can select the project, start typing task name and Titra will complete the rest of that task name. This is good but requires you to go back to Wekan to check what was the exact task name. Could be more convenient if there would be a way to make Titra show all the tasks from the project so I can just select one without having to check for the task name. Preferably, mouse-only-clicking should be more convenient than having to memorize some keyboard shortcut.

**Comment by faburem** [comment]
I agree, this is a good idea however we have to explore how we can do this from a UI/UX perspective. This might be a feature we can only enable for desktop usage due to the space limitation on mobile devices.

**Comment by faburem** [comment]
Hi,
what do you think about this design proposal? We would add a new button next to the task input which opens a modal where all task sources are displayed with tabs for each source. It can be filtered / sorted and used for the task input by selecting an item.
<img width="1363" alt="Screenshot 2021-01-03 at 17 54 57" src="https://user-images.githubusercontent.com/11456790/103484146-d53b8380-4dec-11eb-9338-f86c56e40130.png">

**Comment by faburem** [comment]
The final implementation of this feature is available in titra version 0.40.0 🎉

**Comment by nikolay-martynov** [comment]
This is just perfect! Thank you very much!
