### ISSUE TITLE
More convenient Wekan project import

### ISSUE THREAD

**Issue by nikolay-martynov** [kromitgmbh/titra#43]
When importing project from Wekan you select either columns to import or swimlanes to import. Usually, number of columns is small but number of swimlanes could be significantly larger. Both columns and swimlanes are displayed without any alignment or sorting. It makes it hard find and select swimlanes you need. If you use swimlanes for projects in Wekan then importing plenty of those into Titra could be very cumbersome because it is kind of hard to find swimlanes you need.
Instead, each swimlane could be on each own line. Additionally, swimlanes could be displayed in alphabetical order. This could make the process much easier.
![Screenshot 2020-12-24 092052](https://user-images.githubusercontent.com/13433348/103066170-5adb5a00-45c9-11eb-8f04-16a7849f8e70.png)

**Comment by faburem** [comment]
This will definitely get on our roadmap! Thanks for your feedback, we are not using swimlanes internally that's probably why we didn't come across this on our own.

**Comment by faburem** [comment]
We have completely revamped the Wekan interface configuration in titra version 0.35.0, I hope you like it!
![image](https://user-images.githubusercontent.com/11456790/103175217-95165700-4868-11eb-93f1-76c11d10ac6d.png)
The lists and swimlanes are now displayed in a table view and can be sorted ascending or descending.

**Comment by nikolay-martynov** [comment]
Thank you but something has gone wrong and I don't see swimlanes anymore. I'll file a separate issue

**Comment by nikolay-martynov** [comment]
This is strange but when I import the same project again, then swimlanes are displayed. Thanks, it's more convenient now.
