### ISSUE TITLE
Can't able to signin or register

### ISSUE THREAD

**Issue by surentharp** [kromitgmbh/titra#47]
Hi,

Thank you for providing such a great app.

Today, the online signin for titra is getting connection timed-out. I have attached the console log and error with this for your reference.

Best Regards,
Suren

![Chrome Console Log](https://user-images.githubusercontent.com/5198904/106732293-8cb6f600-6636-11eb-8b72-ea0deaab224a.png)

![Error Displayed](https://user-images.githubusercontent.com/5198904/106732333-97718b00-6636-11eb-987b-4a0ca3badb93.png)

**Comment by faburem** [comment]
Hi,
we are currently facing a DDOS attack on our app.titra.io servers. We wont be able to mitigate that soon and have to wait for the attackers to stop. If someone feels like sponsoring this project we could beef up the servers 💪

Best,
Fabian

**Comment by surentharp** [comment]
Hi Fabian,

Thank you for your response. I truly hope the best for this project, and I will try to contribute of my best. 

Best Regards,
Suren

**Comment by faburem** [comment]
the DDOS attack has been mitigated - all services should be back to normal. I would therefore close this issue!
