### ISSUE TITLE
Serve titra in a subdirectory

### ISSUE THREAD

**Issue by stlehmann** [kromitgmbh/titra#48]
Is it possible to serve Titra in a subdirectory like http://myserver.de/titra? I thought it is possible by setting ROOT_URL but this didn't do the job properly. If I try to register a new user I am redirected to http://myserver.de/join while it should actually be http://myserver.de/titra/join. Is this just a bug or are subdirectories not yet supported?

**Comment by faburem** [comment]
Hi,
we are relying on the Meteor.js framework so we can only support the available options there ([docs](https://docs.meteor.com/environment-variables.html#ROOT-URL)). This kind of subdirectory URL is currently not supported, what about using a subdomain like http://titra.myserver.de?

Best,
Fabian

**Comment by stlehmann** [comment]
@faburem Thanks for your answer. Using a subdomain is definetly an option but requires to get our IT involved. Subdirectories are a nice and easy way to separate webapps without changing DNS. As many frameworks support this and as there is a dedicated ROOT_URL parameter I suspected there might be a bug here.

**Comment by faburem** [comment]
sorry to disappoint :( can we close this issue?

**Comment by stlehmann** [comment]
No worries. Huge thanks for this package and for the work you put into it. I like it and will use it more often in the future.
