### ISSUE TITLE
ERR_CONNECTION_TIMED_OUT error

### ISSUE THREAD

**Issue by surentharp** [kromitgmbh/titra#49]
Hi Fabian,

I can be able to access the titra from mobile, but when I browse using my static IP network I'm receiving "ERR_CONNECTION_TIMED_OUT". Do you know any probable cause for this?

Best Regards,
Suren

**Comment by faburem** [comment]
Hi Suren,
do you refer to our free hosted version at https://app.titra.io?
It is currently up and running without any issues - maybe your IP is in a blacklist? We recently added firewall rules to mitigate a DDOS attack on our servers.

You can check your IP with this service for example:
https://whatismyipaddress.com/blacklist-check

Best regards,
Fabian

**Comment by surentharp** [comment]
Hi Fabin,

Thank you for your kind response. As you mentioned, I was referring to your free hosted version (https://app.titra.io)

Now, suddenly the web application (app.titro.io) is accessible, may be the problem was with my ISP. For your information, I checked my IP for blacklist, and it was not in their database.

Thank you.

Best Regards,
Suren
