### ISSUE TITLE
No Wekan Integration Section/Checkbox in Settings

### ISSUE THREAD

**Issue by CaptainPackers** [kromitgmbh/titra#51]
I have no Wekan Integration section or checkbox on my local docker installation of titra. About page says I am running version 0.44.1. Only options are 

- titra API token
- Siwapp URL
- Siwapp API token
- URL of the Zammad instance
- Zammad Personal Access Token

**Comment by faburem** [comment]
Hi,
the Wekan integration is project specific, thus there is no global setting for the interface. Instead edit any project from the overview to set up the Wekan integration:
![Screenshot 2021-04-02 at 10 10 38](https://user-images.githubusercontent.com/11456790/113396518-f126d500-939b-11eb-9bea-93ba552e8402.png)
![Screenshot 2021-04-02 at 10 11 23](https://user-images.githubusercontent.com/11456790/113396554-fdab2d80-939b-11eb-8c48-4b5bcf857378.png)

Best regards,
Fabian

**Comment by CaptainPackers** [comment]
Hi Fabian,

Thanks for the quick reply. 
The Wekan integration section is still conspicuously missing from my edit project settings.
I have attached a screenshot.
![Screenshot_20210402_083315](https://user-images.githubusercontent.com/7439853/113417956-86bd6700-9392-11eb-9e74-4e74bcbc1be3.png).
Any thoughts on how I can resolve this?
Can you post your docker-compose.yml file here? 
Do you want me to post mine here?

Regards,
CaptainPackers

**Comment by faburem** [comment]
Hi again,
you might have to enable the Wekan interface first. If you have not done so already, first claim admin rights:

https://titra.io/en/wiki/claiming-admin-rights/

Then change the Globalsettings under Administration (set the "Enable Wekan integration?" to true).

https://titra.io/en/wiki/global-settings/

We might change this default setting to true in the future to improve on-boarding for new users.

**Comment by CaptainPackers** [comment]
I was not an admin. I had to claim admin rights as described in the wiki. Then and only then was the Administration menu option available. However, the enable Wekan integration option was already set to true. I saved the settings anyway, even restarted Titra, but there is no change in either the indidvidual Project settings or the Global settings. The option to provide the Wekan URL is still conspicuously missing. What else can I try?

**Comment by ddeenniiss** [comment]
same issue here. Wekan intergration is set to true but there is no option to enable to a project.

**Comment by faburem** [comment]
Bumping this to a potential bug. We have changed the Wekan interface setting from a per-user basis to a global setting recently. I will do some more tests with a fresh titra install and update this issue as I have more information.

**Comment by CaptainPackers** [comment]
Should I update my Docker image now

**Comment by faburem** [comment]
Yes, if you update to the latest version (0.46.0) the Wekan interface settings should appear properly!

**Comment by CaptainPackers** [comment]
So the integration url text box is there now, but I couldn't get titra to accept the url if I specified a port. In other words, if wekan wasn't running on the default port of 80 and the port had to be specified, titra wouldn't accept it

**Comment by faburem** [comment]
titra is making a regular http request to the Wekan instance, so it shouldn't matter on which port it is running if the URL is provided correctly. Did you make sure to follow our setup guide in the wiki https://github.com/faburem/titra/wiki/Wekan-integration ? That should already copy the correct URL for you!

**Comment by CaptainPackers** [comment]
finally got this working, but not until I installed a wekan docker container. I could not get titra to accept the wekan url while it was installed as a snap. This is more likely due to my ignorance about snap networking. It seems like docker is more open with better docker-compose.yml examples. I used a variation of docker-compose.yml from [here](https://github.com/wekan/wekan/blob/master/docker-compose.yml), modified to suit my network. Please consider this issue closed, and thanks for titra and for supporting it.

**Comment by ddeenniiss** [comment]
For me, it's not visible...

**Comment by CaptainPackers** [comment]
Make sure you have the newest image (version 0.46.0) and that you claim admin rights (url/claim/admin)
