### ISSUE TITLE
Cannot reset password.

### ISSUE THREAD

**Issue by louistb** [kromitgmbh/titra#55]
Hi,

I have been using your hosted app for a moment now to track time, its amazing thanks a lot for it.

But i forgot my password and i need to reset it and it doesn't seem its sending me the reset password email.

Thanks

**Comment by faburem** [comment]
Thanks for bringing this to my attention. We have not set up the SMTP service to send E-mails yet. I am currently pushing a new version of titra which will fix this on the hosted environment.

**Comment by louistb** [comment]
Amazing, thanks again for this amazing tool :)

**Comment by louistb** [comment]
I was able to reset my password, thanks a lot.

Any way to give you guys some donations for this project ?

Thanks

**Comment by faburem** [comment]
You can become Github Sponsor here: https://github.com/sponsors/kromitgmbh

**Comment by louistb** [comment]
Done :)
