### ISSUE TITLE
Nginx configuration

### ISSUE THREAD

**Issue by ddeenniiss** [kromitgmbh/titra#56]
I do some tests but with a simple http://myhost:3000 but i have some errors

Is there a simple configuration for nginx ?

**Comment by faburem** [comment]
Hi,
you don't need nginx to serve titra on port 3000, the web application is already exposed on that port. I assume you are using the Docker version of titra? It might help to take a look at the wiki, specifically the page about [Environment variables](https://titra.io/en/wiki/environment-variables/).

Best,
Fabian

**Comment by faburem** [comment]
Do you have any further questions or can we close this issue?
