### ISSUE TITLE
Get running timers and stop by using API.

### ISSUE THREAD

**Issue by louistb** [kromitgmbh/titra#64]
Thanks again for the amazing software you guys have created.
Its part of my everyday workflow has a freelancer and its essential to me <3

This is more a feature suggestion then a bug btw.

Would it be possible to return a list of running timer from the API, and eventually stop and save them.

Thanks again

**Comment by faburem** [comment]
Hi and thanks for your feedback - it is really appreciated!
I will add your feature request to the roadmap, but we have currently some big changes cooking up in connection to our migration to bootstrap 5 🥳

**Comment by faburem** [comment]
Implemented and shipped in titra version 0.52.0 🎉

**Comment by louistb** [comment]
You guys are amazing, thanks
