### ISSUE TITLE
LDAP authentication support

### ISSUE THREAD

**Issue by Verfuchst** [kromitgmbh/titra#67]
Hello,
i saw on the roadmap there will be support in the future for ldap (https://github.com/kromitgmbh/titra/projects/1#card-30317593). Is it something that will happen soon? Because it would be a big improvement to get this in bigger infrastructures.

**Comment by faburem** [comment]
Hi and thanks for reaching out!
we have a hackathon planned for next week where we want to check off some of the items in the titra roadmap. Our priority is support for custom fields, but once we have that figured out we can focus on new integrations. We cannot provide an ETA, but [sponsoring our work ](https://github.com/sponsors/kromitgmbh) is a good motivation for the team 🤓

**Comment by faburem** [comment]
LDAP support will be released as the first official titra extension later this week 🥳

**Comment by faburem** [comment]
LDAP user authentication is now supported in titra, with the first official extension published to our brand new [extension store](https://titra.io/en/enterprise/)!
