### ISSUE TITLE
clearing date from DatePicker throws error

### ISSUE THREAD

**Issue by thomas-kromit** [kromitgmbh/titra#68]
[ERROR: Uncaught TypeError: Cannot read property '$' of null @ Tue Jul 13 2021 14:13:40 GMT+0200 (Central European Summer Time)] { 
   "file": "**/imports/ui/pages/tracktime.js**", 
   "onLine": **114**, 
   "browserInfo": { 
   "browser": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36 OPR/76.0.4017.227", 
   "userId": "AkvRvz6AwMmL9CKpv", 
   "url": "http://localhost:3000/tracktime?date=2021-07-13", 
   "resolution": "2560x1440" 
   } 
 }

**Comment by faburem** [comment]
fixed in titra 0.53.0!
