### ISSUE TITLE
Update time to wekan

### ISSUE THREAD

**Issue by GammaPi** [kromitgmbh/titra#71]
It would be better if titra could have options to update working hours and start/end time to wekan.

**Comment by faburem** [comment]
Thanks for the suggestion, but we currently only have an inbound interface to import cards from Wekan. This interface has been built before Wekan officially released a REST API so we are currently not using it. Moving to the official REST API would be a breaking change for all titra users so we have to consider carefully if / how we want to make this transition.

**Comment by faburem** [comment]
I am closing this issue due to feasibility concerns. We would need a mapping on the task <> card level to enable such an interface plus it would require implementing the WeKan REST API as mentioned before which does not seem viable from a cost/benefit perspective.
