### ISSUE TITLE
Cannot Login

### ISSUE THREAD

**Issue by louistb** [kromitgmbh/titra#76]
Hi,

Just wanted to know if the app.titra service was having some downtime ?

I cannot seem to login since yesterday night.

Thanks A lot

**Comment by louistb** [comment]
i just got a login.500 error to be more precise.

Thanks

**Comment by faburem** [comment]
Thanks for letting us know. Should be fixed now 💪

**Comment by louistb** [comment]
You guys are the BEST thanks
