### ISSUE TITLE
Error: Cannot find module 'node:http

### ISSUE THREAD

**Issue by ChrisB85** [kromitgmbh/titra#83]
Hi,

I have just updated docker instance of titra to newest version (0.60.0) and it's not starting properly. From log:

`Error: Cannot find module 'node:http'
titra    | Require stack:
titra    | - /app/bundle/programs/server/boot.js
titra    | - /app/bundle/main.js
titra    |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
titra    |     at Function.resolve (internal/modules/cjs/helpers.js:98:19)
titra    |     at Object.require (/app/bundle/programs/server/boot.js:286:34)
titra    |     at makeInstallerOptions.fallback (packages/modules-runtime.js:618:18)
titra    |     at Module.require (packages/modules-runtime.js:244:14)
titra    |     at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:52:22)
titra    |     at module (packages/modules.js:1335:192)
titra    |     at fileEvaluate (packages/modules-runtime.js:336:7)
titra    |     at Module.require (packages/modules-runtime.js:238:14)
titra    |     at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:52:22)
titra    |     at module (imports/api/timecards/methods.js:1:239)
titra    |     at fileEvaluate (packages/modules-runtime.js:336:7)
titra    |     at Module.require (packages/modules-runtime.js:238:14)
titra    |     at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:52:22)
titra    |     at module (imports/startup/server/index.js:1:262)
titra    |     at fileEvaluate (packages/modules-runtime.js:336:7) {
titra    |   code: 'MODULE_NOT_FOUND',
titra    |   requireStack: [ '/app/bundle/programs/server/boot.js', '/app/bundle/main.js' ]
titra    | }
titra    | /app/bundle/programs/server/node_modules/fibers/future.js:280
titra    |                                              throw(ex);
titra    |                                              ^
`

**Comment by faburem** [comment]
Hi,
thanks - a fix is already being rolled out. Please update to 0.60.1 to resolve it.

Best,
Fabian

**Comment by faburem** [comment]
It is actually fixed in titra version 0.60.2 - I had to bust the Github Actions cache to push a clean release to Docker hub.

**Comment by faburem** [comment]
I assume this can be closed, if you still experience any issues feel free to open another issue!
