### ISSUE TITLE
TImer not running + New input field

### ISSUE THREAD

**Issue by louistb** [kromitgmbh/titra#87]
Hi guys, 

it seems like the timer is not going up right now its stuck at 00:00:00 :(

Also there is a input field that seems to be there and that was not there before.

No rush, just wanted to point it out.

Happy holidays to the whole team  :)

![image](https://user-images.githubusercontent.com/2654241/147419924-9263d3fe-e830-4c6a-a471-e6c7db8445fc.png)

Thanks :)

**Comment by faburem** [comment]
Hi,
thanks for reporting this! We introduced a regression with the new timer features in titra 0.63.0 - the fix is rolling out now with version 0.64.0! If you are still experiencing issues please feel free to re-open this issue or create a new one.

Happy holidays,
Fabian

**Comment by louistb** [comment]
Thanks again for this amazing tool :)
