### ISSUE TITLE
Add 'Customer' to report/details

### ISSUE THREAD

**Issue by nikolay-martynov** [kromitgmbh/titra#88]
Projects have field `Customer`. Also, you can filter details by customer. However, when exporting to CSV/Excel there is no `Customer` field. Please add field `Customer` from project to `Details` -> `Detailed` (and maybe others) report.

![image](https://user-images.githubusercontent.com/13433348/147539772-313aedd7-df4b-4a71-a21a-5a578999b12e.png)

Additionally or alternatively, please export custom fields. You can define custom field for projects then set value of the field for each project but this data is not exported.

What I try to achieve is to classify all projects into few categories and then see how much time was spent in each category. This is in addition to usual Project/Task breakdown. Like you are working on many projects during the week and doing many tasks for each project. Then, say monthly, you need to check how much time was spent on projects in this or that category. But at the same time you still need ability to 'drill down' and see what exactly you've done in the particular category (so you can't use Project as category and use Project as Project and Task as Task). Either customer or custom fields can be used for that. But unfortunately, none of those get exported.

**Comment by faburem** [comment]
This enhancement has just shipped in titra version 0.65.0! There are two new administration settings which allow to enable/disable the display of the customer and/or custom fields:

![image](https://user-images.githubusercontent.com/11456790/147857367-3ef26411-de70-461f-a67c-157ac79b3b55.png)

If you encounter any issues with this new feature feel free to open a new issue!

Happy new year 🎆

**Comment by nikolay-martynov** [comment]
Works perfectly. Thank you very much, Fabian!
