### ISSUE TITLE
Error on newly installed instance of titra

### ISSUE THREAD

**Issue by jsteyn** [kromitgmbh/titra#89]
Hi there
I would very much like to evaluate titra for use by my team. I used the suggested production docker-compose.yml to get a running instance of titra up and going. However, when I then access the server from a browser I get the following error message on the server while the browser screen stays blank. I would really appreciate any help to get this server running:

<pre>
titra         | [ERROR: [ostrio:flow-router-extra] [route.wait] Promise not resolved @ Wed Jan 12 2022 00:20:36 GMT+0000 (Greenwich Mean Time)] {
titra         |   "browserInfo": {
titra         |     "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36",
titra         |     "userId": null,
titra         |     "url": "http://192.168.1.28:3000/",
titra         |     "resolution": "1600x900"
titra         |   },
titra         |   "stack": {}
titra         | }
titra         | [ERROR: [ostrio:flow-router-extra] [route.wait] Promise not resolved @ Wed Jan 12 2022 00:20:36 GMT+0000 (Greenwich Mean Time)] {
titra         |   "browserInfo": {
titra         |     "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36",
titra         |     "userId": null,
titra         |     "url": "http://192.168.1.28:3000/",
titra         |     "resolution": "1600x900"
titra         |   },
titra         |   "stack": {}
titra         | }
titra         | [ERROR: [ostrio:flow-router-extra] [route.wait] Promise not resolved @ Wed Jan 12 2022 00:20:36 GMT+0000 (Greenwich Mean Time)] {
titra         |   "browserInfo": {
titra         |     "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36",
titra         |     "userId": null,
titra         |     "url": "http://192.168.1.28:3000/",
titra         |     "resolution": "1600x900"
titra         |   },
titra         |   "stack": {}
titra         | }
titra         | [ERROR: [ostrio:flow-router-extra] [route.wait] Promise not resolved @ Wed Jan 12 2022 00:20:36 GMT+0000 (Greenwich Mean Time)] {
titra         |   "browserInfo": {
titra         |     "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36",
titra         |     "userId": null,
titra         |     "url": "http://192.168.1.28:3000/",
titra         |     "resolution": "1600x900"
titra         |   },
titra         |   "stack": {}
titra         | }
titra         | [ERROR: [ostrio:flow-router-extra] [route.wait] Promise not resolved @ Wed Jan 12 2022 00:20:36 GMT+0000 (Greenwich Mean Time)] {
titra         |   "browserInfo": {
titra         |     "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36",
titra         |     "userId": null,
titra         |     "url": "http://192.168.1.28:3000/",
titra         |     "resolution": "1600x900"
titra         |   },
titra         |   "stack": {}
titra         | }
titra         | [ERROR: [ostrio:flow-router-extra] [route.wait] Promise not resolved @ Wed Jan 12 2022 00:20:36 GMT+0000 (Greenwich Mean Time)] {
titra         |   "browserInfo": {
titra         |     "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36",
titra         |     "userId": null,
titra         |     "url": "http://192.168.1.28:3000/",
titra         |     "resolution": "1600x900"
titra         |   },
titra         |   "stack": {}
titra         | }
titra         | [ERROR: [ostrio:flow-router-extra] [route.wait] Promise not resolved @ Wed Jan 12 2022 00:20:36 GMT+0000 (Greenwich Mean Time)] {
titra         |   "browserInfo": {
titra         |     "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36",
titra         |     "userId": null,
titra         |     "url": "http://192.168.1.28:3000/",
titra         |     "resolution": "1600x900"
titra         |   },
titra         |   "stack": {}
titra         | }
titra         | [ERROR: [ostrio:flow-router-extra] [route.wait] Promise not resolved @ Wed Jan 12 2022 00:20:36 GMT+0000 (Greenwich Mean Time)] {
titra         |   "browserInfo": {
titra         |     "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36",
titra         |     "userId": null,
titra         |     "url": "http://192.168.1.28:3000/",
titra         |     "resolution": "1600x900"
titra         |   },
titra         |   "stack": {}
titra         | }
titra         | [ERROR: [ostrio:flow-router-extra] [route.wait] Promise not resolved @ Wed Jan 12 2022 00:20:36 GMT+0000 (Greenwich Mean Time)] {
titra         |   "browserInfo": {
titra         |     "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36",
titra         |     "userId": null,
titra         |     "url": "http://192.168.1.28:3000/",
titra         |     "resolution": "1600x900"
titra         |   },
titra         |   "stack": {}
titra         | }
titra         | [ERROR: [ostrio:flow-router-extra] [route.wait] Promise not resolved @ Wed Jan 12 2022 00:20:36 GMT+0000 (Greenwich Mean Time)] {
titra         |   "browserInfo": {
titra         |     "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36",
titra         |     "userId": null,
titra         |     "url": "http://192.168.1.28:3000/",
titra         |     "resolution": "1600x900"
titra         |   },
titra         |   "stack": {}
titra         | }
titra         | [ERROR: Uncaught TypeError: $(...).popover is not a function @ Wed Jan 12 2022 00:20:36 GMT+0000 (Greenwich Mean Time)] {
titra         |   "file": "http://192.168.1.28:3000/b4887e834c3a1604d8a49a90e5283a49ccce4f43.js?meteor_js_resource=true",
titra         |   "onLine": 206,
titra         |   "browserInfo": {
titra         |     "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36",
titra         |     "userId": null,
titra         |     "url": "http://192.168.1.28:3000/signIn",
titra         |     "resolution": "1600x900"
titra         |   }
titra         | }
</pre>

**Comment by faburem** [comment]
Hi,
thanks for reaching out!
Did you make sure to set your ROOT_URL to the IP you are trying to access it from? Based on your logs it should be set to http://192.168.1.28:3000/

Best regards,
Fabian

**Comment by jsteyn** [comment]
Hi Fabian
Thank you for your very quick response. I now feel like a bit of an idiot. I did set the ROOT_URL, but I didn't add the port at the end. Now that I have added it, it seems to work.
Thanks again
Jannetta

**Comment by faburem** [comment]
no worries, you are very welcome! I am glad it worked 🕺
