### ISSUE TITLE
Integrating titra with Wekan

### ISSUE THREAD

**Issue by jsteyn** [kromitgmbh/titra#90]
I'm following the instructions on integrating titra with Wekan on this page: https://github.com/kromitgmbh/titra/wiki/Wekan-integration

However, I do not have the "Setting" item as shown in this screenshot. In stead I have a "Details" option.
![Screenshot](https://github.com/kromitgmbh/titra/wiki/images/titra_enable_wekan_integration.png)

There is a 'Settings' option on the menu when clicking on the circle with one's initials on the far right hand top corner of the screen but that page does not have the 'Enable Wekan Integration' option.

Can you please advise?

**Comment by faburem** [comment]
Thanks for bringing this to our attention, it looks like the docs need some update since things have changed a bit in the UI in the last couple of months. You can find the Wekan setting now in the administration page. Please note that you have to claim admin rights first as documented in the wiki to see this page.
![Screenshot_20220112-183646_Chrome.jpg](https://user-images.githubusercontent.com/11456790/149192772-fcdeb212-e533-4d89-a145-78f18575881c.jpg)

**Comment by jsteyn** [comment]
Hi Fabian

Thanks again for your help. (I hope I'm not driving you nuts with my questions). I managed to claim administrator rights and then I managed to follow the instructions further to obtain the URL. However, when I paste the URL in the 'Wekan integration' field, it does not authenticate. To test, I pasted the URL in a browser window and it seems to work as all of the information is downloaded in json format.

Regards
Jannetta

**Comment by faburem** [comment]
Hi Jannetta,
I am happy to help - did you see the prerequisites part in the wiki about the Wekan integration:
![image](https://user-images.githubusercontent.com/11456790/149284101-2b66ed2f-bac4-410b-97ec-b56689ba47fd.png)

I am not sure about your setup but I assume that you are also hosting Wekan in a docker container, in that case you can check out the [Wekan docker example](https://github.com/wekan/wekan/blob/1617577378fc17ca09fd3ef34f24e02c2889aa9f/docker-compose.yml#L295-L301) on how to enable the proper CORS settings.

Best,
Fabian

**Comment by jsteyn** [comment]
Hi Fabian
I was running wekan as a snap app before but I have now changed to running it in a docker. I have checked the CORS variables. However, I am still not having any luck integrating titra with Wekan. I include some screen shots if it will help

![wekan_cors](https://user-images.githubusercontent.com/6432530/149453403-5a4e8b54-504b-4675-816d-701a702d33b8.png)
![titra_wekanenable](https://user-images.githubusercontent.com/6432530/149453405-5e6f7567-4543-44c9-9c78-9935e4d942fe.png)
.

**Comment by faburem** [comment]
Hi Jannetta,
can you maybe post a screenshot of your browser console output when you are trying to connect your Wekan instance? That would probably provide some more insights and help us troubleshooting.

Best regards,
Fabian

**Comment by faburem** [comment]
Did you make sure you can ping the host floki.local from 192.168.1.28? Titra is checking the format and connection before accepting the input therefore you can not save it.

**Comment by faburem** [comment]
okay, in that case I am pretty sure that the titra docker container does not know how to resolve floki.local. Docker networking is a bit tricky, basically you have to make sure that both containers are in the same network and can resolve/ping each other, here is a brief tutorial on this topic: https://docs.docker.com/network/network-tutorial-standalone/ .

**Comment by faburem** [comment]
I assume this issue is either resolved or not relevant any more. Feel free to open it again or create a new issue if you still have  this or other problems!
