### ISSUE TITLE
Some settings are reset when editing project

### ISSUE THREAD

**Issue by nikolay-martynov** [kromitgmbh/titra#91]
When you try to edit existing project then the following settings get reset to some default/empty values. Instead, it would help a lot if project edit form would use current project settings when it is loaded.

- Custom fields
- Public project (project visibility setting)
- Wekan swimlanes

**Comment by nikolay-martynov** [comment]
I did little experimenting and it seems that wekan swimlanes are reset if you do not click "Check" button and are preserved if you click it. It might be better to always populate current picks as a default value. Otherwise, if you forget to click "Check" then it gets reset and you find this out much later and then have to edit project again and try to remember what were the swimlane picks.

**Comment by faburem** [comment]
Hi,
thanks for the detailed issue report! Please try it again with version 0.67.0, the public project setting should now update correctly and selecting/deselecting a wekan list will save the project.
I could not really reproduce the issue with the custom fields, they were always displayed correctly for me. If you still experience this issue please reopen or create a new one with more details on this one.

Thanks,
Fabian
