### ISSUE TITLE
Ability to edit custom field

### ISSUE THREAD

**Issue by nikolay-martynov** [kromitgmbh/titra#92]
For a String custom field you can specify multiple values separated by comma and then Titra allows you to select one of those values from a drop box. That's perfect. However, since there is no edit button for a custom fields, it is not clear how to add another allowed value. When you go to "Administrative -> Custom fields" then trash button is displayed and you can delete the field. However, if you have data tracked then it's a bad option to drop the field and recreate it with a new list of allowed values. Instead, it would be nice to have an edit button. The edit form might disallow changing the field type if this is a problem but it should allow appending additional values to be allowed to be selected.

**Comment by faburem** [comment]
This new feature has shipped in titra 0.68.0! Please open a new issue if you encounter any issues.

**Comment by nikolay-martynov** [comment]
Works great. Thank you
