### ISSUE TITLE
Wekan swimlane selection is reset on project edit

### ISSUE THREAD

**Issue by nikolay-martynov** [kromitgmbh/titra#93]
1.  Have a project with link to wekan and swimlane selected
![image](https://user-images.githubusercontent.com/13433348/150793419-4cda5922-f85b-44e3-914c-a1f73a8168b7.png)
2. Try to track time for this project and you see that wekan tasks from specified swimlane are suggested
![image](https://user-images.githubusercontent.com/13433348/150793677-3d65e63b-85cf-49de-85d7-0ceacec6f882.png)
3. Edit project again, change nothing and just click "Save" button
![image](https://user-images.githubusercontent.com/13433348/150793992-bfe3e7b6-a335-4d13-8d2d-fcea494ef551.png)
4. Try to track time for the project and you'll see that no tasks from wekan are suggested
![image](https://user-images.githubusercontent.com/13433348/150794239-bb7d0f40-dd4e-426a-b1ff-489671b62493.png)
5. Edit project again, click check wekan button and see that no swimlane, that was initially selected, is selected now
![image](https://user-images.githubusercontent.com/13433348/150794465-22693b85-a7ac-4e59-97c8-22b8da316e32.png)

User might have edited one of the dozen of fields. It is counter intuitive to press "Check" if you have not changed Wekan API URL. And without clicking the button, integration with wekan breaks. Instead, Titra should just preserve old settings if user did not change API URL and did not press "Check". Alternatively, some message should be displayed to ask to click "Check". Or the field "API URL" could have some warning to remind to press the button.

**Comment by faburem** [comment]
This should be fixed in titra version 0.68.0. Please feel free to open a new ticket if the issue still persists and thanks again for the good bug report!

**Comment by nikolay-martynov** [comment]
Settings are preserved now. Thank you!
