### ISSUE TITLE
Problems Changing User Password

### ISSUE THREAD

**Issue by thtuerk** [kromitgmbh/titra#95]
First of all: many thanks for developing this useful tool. I discovered it a few days ago and it is nearly exactly what I was looking for. Many thanks! Unluckily I ran into trouble though, when trying to change the dummy password of the user in my test-installation.

### Problem Description

The _Change password_ in the dialog opened by _Profile - Change Password_ seems to be broken on 0.68.0. Whatever I enter (wrong current password, new password with correct or incorrect repetition, missing new passwords) there is no reaction by Titra on pressing the _Change password_ button and the password is not changed.

#### Test description
I tried with current versions of Firefox and Chrome on Ubuntu 21.10 and Windows 10 and additionally Edge on Windows 10. Moreover, I checked various older docker images. I always get the behavior described above. I got the impression that nothing is executed by pressing this button.

### Possible fix
I looked very briefly into it and noticed that in contrast to other buttons on other forms, the _Change password_ one has no ID. Adding some debug code to the event ` 'click #changePassword'` in `changePassword.js` confirmed my suspicion that this event never fires. Therefore, I added the id `changePassword` to the button. This seems to have done the trick for me. It is working now. 

Nowever, I have no clue, whether adding an ID is a sensible thing. Anyhow, for your ease I will create a pull request in case it is a sensible fix. 

Many thanks for developing Titra and making it available.

Thomas Tuerk

**Comment by faburem** [comment]
awesome! thanks for your detailed report and even including a pull request! We will review it asap and merge it in the next release 💪

**Comment by faburem** [comment]
this should be fixed in titra 0.69.0! Thanks again for reporting this issue and submitting a PR! If you are still encountering a problem feel free to open another issue.

**Comment by thtuerk** [comment]
I can confirm that it is fixed in Titra 0.69.0. Many thanks!
